// ---------------------------------------------------------------------------
// The Board — the starter library.
//
// This is a fast start, NOT a source of truth. Pricing, API details and which
// tool is currently best all move faster than any snapshot of them; every
// field here is editable in the app, and the whole point of `addedAt` is to
// make a stale entry obvious. Correct these as you go.
//
// Ranks and features are deliberately left empty. The leaderboard is personal
// — it starts blank and is filled by you, not inherited from someone else's
// opinion.
// ---------------------------------------------------------------------------

import type { SeedTool } from "./types";

export const SEED_TOOLS: SeedTool[] = [
  // ----- LLM ---------------------------------------------------------------
  {
    name: "Claude",
    url: "https://claude.ai",
    summary: "Anthropic's assistant — long-context reasoning, writing and code.",
    group: "AI",
    category: "LLM",
    tags: ["vision", "long-context", "reasoning", "coding"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; Pro/Max subscription; API billed per token",
  },
  {
    name: "ChatGPT",
    url: "https://chatgpt.com",
    summary: "OpenAI's assistant, with image generation and browsing built in.",
    group: "AI",
    category: "LLM",
    tags: ["vision", "reasoning", "image-gen", "browsing"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; Plus/Pro subscription; API billed per token",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com",
    summary: "Google's assistant — very large context and strong multimodal input.",
    group: "AI",
    category: "LLM",
    tags: ["vision", "long-context", "audio-in", "video-in"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; AI Pro/Ultra subscription; API billed per token",
  },
  {
    name: "Grok",
    url: "https://grok.com",
    summary: "xAI's assistant, wired into X for real-time posts.",
    group: "AI",
    category: "LLM",
    tags: ["vision", "realtime", "reasoning"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; X Premium / SuperGrok; API billed per token",
  },
  {
    name: "DeepSeek",
    url: "https://www.deepseek.com",
    summary: "Open-weight reasoning models at a fraction of frontier API pricing.",
    group: "AI",
    category: "LLM",
    tags: ["reasoning", "coding", "cheap-api"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free chat; very low per-token API; weights on Hugging Face",
  },
  {
    name: "Qwen",
    url: "https://chat.qwen.ai",
    summary: "Alibaba's open model family — text, vision and coding variants.",
    group: "AI",
    category: "LLM",
    tags: ["vision", "open-weights", "coding", "multilingual"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free to self-host; hosted API via Alibaba Cloud",
  },
  {
    name: "Llama",
    url: "https://www.llama.com",
    summary: "Meta's open-weight family — the default base for local fine-tunes.",
    group: "AI",
    category: "LLM",
    tags: ["open-weights", "vision", "fine-tunable"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free weights under Meta's community licence",
  },
  {
    name: "Mistral",
    url: "https://mistral.ai",
    summary: "European lab with both open weights and a hosted API.",
    group: "AI",
    category: "LLM",
    tags: ["open-weights", "coding", "cheap-api"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Open weights free; hosted API per token",
  },
  {
    name: "Kimi",
    url: "https://kimi.moonshot.cn",
    summary: "Moonshot's open agentic model — strong tool use and long context.",
    group: "AI",
    category: "LLM",
    tags: ["open-weights", "long-context", "agentic"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Perplexity",
    url: "https://www.perplexity.ai",
    summary: "Search-first answers with citations — research rather than chat.",
    group: "AI",
    category: "LLM",
    tags: ["search", "citations", "research"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; Pro subscription; Sonar API",
  },

  // ----- Image -------------------------------------------------------------
  {
    name: "Midjourney",
    url: "https://www.midjourney.com",
    summary: "The aesthetic benchmark — best-looking output with the least prompting.",
    group: "AI",
    category: "Image",
    tags: ["aesthetic", "style-reference", "upscale"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
    pricingNote: "From ~$10/mo; no free tier",
  },
  {
    name: "Flux",
    url: "https://blackforestlabs.ai",
    summary: "Black Forest Labs' models — open weights plus a paid hosted API.",
    group: "AI",
    category: "Image",
    tags: ["open-weights", "photoreal", "text-in-image", "inpainting"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Schnell/dev weights free; Pro via API credits",
  },
  {
    name: "Stable Diffusion",
    url: "https://stability.ai",
    summary: "The open-weights workhorse — every LoRA and ControlNet targets it.",
    group: "AI",
    category: "Image",
    tags: ["open-weights", "loras", "controlnet", "fine-tunable"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Weights free; Stability API is paid",
  },
  {
    name: "Nano Banana",
    url: "https://gemini.google.com",
    summary: "Google's image model — conversational editing that keeps the subject.",
    group: "AI",
    category: "Image",
    tags: ["editing", "character-consistency", "conversational"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "In Gemini free tier; API per image",
  },
  {
    name: "Ideogram",
    url: "https://ideogram.ai",
    summary: "The one that gets text inside the image right — posters and logos.",
    group: "AI",
    category: "Image",
    tags: ["text-in-image", "typography", "logos"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Limited free credits; paid plans",
  },
  {
    name: "Recraft",
    url: "https://www.recraft.ai",
    summary: "Vector and brand-consistent output — real SVG, not a traced raster.",
    group: "AI",
    category: "Image",
    tags: ["vector", "svg", "brand-style", "text-in-image"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Leonardo.Ai",
    url: "https://leonardo.ai",
    summary: "Model zoo plus a canvas — game and concept-art oriented.",
    group: "AI",
    category: "Image",
    tags: ["concept-art", "canvas", "model-training"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Daily free credits; paid tiers",
  },
  {
    name: "Krea",
    url: "https://www.krea.ai",
    summary: "Realtime canvas — the image updates as you draw and type.",
    group: "AI",
    category: "Image",
    tags: ["realtime", "canvas", "upscale", "enhance"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Adobe Firefly",
    url: "https://firefly.adobe.com",
    summary: "Commercially-safe training data, and it lives inside Photoshop.",
    group: "AI",
    category: "Image",
    tags: ["commercial-safe", "photoshop", "generative-fill"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Monthly generative credits; included with Creative Cloud",
  },
  {
    name: "Freepik",
    url: "https://www.freepik.com/ai",
    summary: "Many models behind one subscription — useful for comparing cheaply.",
    group: "AI",
    category: "Image",
    tags: ["multi-model", "stock", "upscale"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },

  // ----- Video -------------------------------------------------------------
  {
    name: "Sora",
    url: "https://sora.com",
    summary: "OpenAI's video model — strong physics and native audio.",
    group: "AI",
    category: "Video",
    tags: ["text-to-video", "audio", "remix", "cameo"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Included with ChatGPT plans; API per second",
  },
  {
    name: "Veo",
    url: "https://deepmind.google/models/veo",
    summary: "Google's video model — synchronised dialogue and sound effects.",
    group: "AI",
    category: "Video",
    tags: ["text-to-video", "audio", "lipsync", "image-to-video"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "In Gemini plans; API per second via Vertex",
  },
  {
    name: "Runway",
    url: "https://runwayml.com",
    summary: "The editor's tool — video-to-video, motion brush, real timeline control.",
    group: "AI",
    category: "Video",
    tags: ["video-to-video", "motion-brush", "editing", "camera-control"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Limited free credits; paid plans",
  },
  {
    name: "Kling",
    url: "https://klingai.com",
    summary: "Kuaishou's model — reliable image-to-video and long clips.",
    group: "AI",
    category: "Video",
    tags: ["image-to-video", "long-clips", "lipsync"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Daily free credits; paid tiers",
  },
  {
    name: "Hailuo (MiniMax)",
    url: "https://hailuoai.video",
    summary: "Punchy motion and character consistency; generous free generations.",
    group: "AI",
    category: "Video",
    tags: ["image-to-video", "character-consistency", "motion"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Seedance",
    url: "https://seed.bytedance.com",
    summary: "ByteDance's video model — multi-shot sequences from one prompt.",
    group: "AI",
    category: "Video",
    tags: ["multi-shot", "image-to-video", "camera-control"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Via AI Gateway / Volcano Engine, per generation",
    notes: "Drives the Seedance Studio app in this hub.",
  },
  {
    name: "Luma Dream Machine",
    url: "https://lumalabs.ai/dream-machine",
    summary: "Fast, fluid motion with keyframe control between two stills.",
    group: "AI",
    category: "Video",
    tags: ["keyframes", "image-to-video", "fast"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Pika",
    url: "https://pika.art",
    summary: "Effect-led and social-first — good for short, punchy edits.",
    group: "AI",
    category: "Video",
    tags: ["effects", "short-form", "image-to-video"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Wan",
    url: "https://github.com/Wan-Video",
    summary: "Alibaba's open-weight video models — the best you can run locally.",
    group: "AI",
    category: "Video",
    tags: ["open-weights", "local", "image-to-video", "comfyui"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free weights; needs a serious GPU",
  },
  {
    name: "HunyuanVideo",
    url: "https://github.com/Tencent/HunyuanVideo",
    summary: "Tencent's open video model — heavy, but fully yours to run.",
    group: "AI",
    category: "Video",
    tags: ["open-weights", "local", "comfyui"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free weights; high VRAM",
  },
  {
    name: "LTX Video",
    url: "https://www.lightricks.com/ltxv",
    summary: "Lightricks' open model built for speed — near-realtime on consumer GPUs.",
    group: "AI",
    category: "Video",
    tags: ["open-weights", "fast", "local", "comfyui"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "none",
    haveKey: false,
  },

  // ----- Music -------------------------------------------------------------
  {
    name: "Suno",
    url: "https://suno.com",
    summary: "Full songs with vocals from a style prompt and lyrics.",
    group: "AI",
    category: "Music",
    tags: ["vocals", "full-song", "stems", "covers"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Daily free credits; paid plans for commercial use",
    notes: "The Soundprint app in this hub writes prompts for it.",
  },
  {
    name: "Udio",
    url: "https://www.udio.com",
    summary: "Suno's closest rival — often cleaner vocals, tighter mixes.",
    group: "AI",
    category: "Music",
    tags: ["vocals", "full-song", "extend", "stems"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "ElevenLabs Music",
    url: "https://elevenlabs.io/music",
    summary: "Studio-grade instrumental and vocal tracks, licensed for commercial use.",
    group: "AI",
    category: "Music",
    tags: ["commercial-safe", "instrumental", "vocals"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Stable Audio",
    url: "https://stableaudio.com",
    summary: "Stability's audio model — sound design and loops more than songs.",
    group: "AI",
    category: "Music",
    tags: ["sound-design", "loops", "open-weights", "instrumental"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Open small model free; hosted tiers paid",
  },
  {
    name: "Riffusion",
    url: "https://www.riffusion.com",
    summary: "Free, fast song generation with a genuinely generous tier.",
    group: "AI",
    category: "Music",
    tags: ["vocals", "full-song", "free-tier"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "ACE-Step",
    url: "https://github.com/ace-step/ACE-Step",
    summary: "Open-weight song generation you can run locally — the open Suno.",
    group: "AI",
    category: "Music",
    tags: ["open-weights", "local", "vocals", "comfyui"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "YuE",
    url: "https://github.com/multimodal-art-projection/YuE",
    summary: "Open full-song generation with lyrics — research-grade, free.",
    group: "AI",
    category: "Music",
    tags: ["open-weights", "local", "vocals", "lyrics"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Mureka",
    url: "https://www.mureka.ai",
    summary: "Song generation with a reference-track mode and an API.",
    group: "AI",
    category: "Music",
    tags: ["vocals", "reference-track", "api"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },

  // ----- Voice -------------------------------------------------------------
  {
    name: "ElevenLabs",
    url: "https://elevenlabs.io",
    summary: "The quality bar for TTS, cloning and dubbing.",
    group: "AI",
    category: "Voice",
    tags: ["tts", "cloning", "dubbing", "multilingual"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "10k free chars/mo; paid tiers by character count",
  },
  {
    name: "Fish Audio",
    url: "https://fish.audio",
    summary: "Fast cloning with an open model lineage and cheap API.",
    group: "AI",
    category: "Voice",
    tags: ["tts", "cloning", "open-weights", "cheap-api"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    notes: "Backs the Voice Studio app in this hub — needs FISH_API_KEY for cloning.",
  },
  {
    name: "Cartesia",
    url: "https://cartesia.ai",
    summary: "Very low latency TTS — the one to use for realtime agents.",
    group: "AI",
    category: "Voice",
    tags: ["tts", "low-latency", "realtime", "cloning"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
  },
  {
    name: "PlayHT",
    url: "https://play.ht",
    summary: "Long-form narration and conversational voices with an API.",
    group: "AI",
    category: "Voice",
    tags: ["tts", "narration", "cloning"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Kokoro",
    url: "https://huggingface.co/hexgrad/Kokoro-82M",
    summary: "Tiny open TTS that runs on CPU and still sounds good.",
    group: "AI",
    category: "Voice",
    tags: ["open-weights", "tts", "local", "lightweight"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Apache licence, 82M params — runs anywhere",
  },
  {
    name: "F5-TTS",
    url: "https://github.com/SWivid/F5-TTS",
    summary: "Open zero-shot voice cloning from a few seconds of reference audio.",
    group: "AI",
    category: "Voice",
    tags: ["open-weights", "cloning", "local", "zero-shot"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Chatterbox",
    url: "https://github.com/resemble-ai/chatterbox",
    summary: "Resemble's open TTS with emotion-exaggeration control.",
    group: "AI",
    category: "Voice",
    tags: ["open-weights", "cloning", "emotion", "local"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Whisper",
    url: "https://github.com/openai/whisper",
    summary: "The default speech-to-text — open weights, runs locally, free.",
    group: "AI",
    category: "Voice",
    tags: ["stt", "transcription", "open-weights", "local", "subtitles"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free local; OpenAI hosted API is cheap per minute",
  },

  // ----- Agent Coding ------------------------------------------------------
  {
    name: "Claude Code",
    url: "https://claude.com/claude-code",
    summary: "Terminal-native agent that reads and edits a whole repo.",
    group: "AI",
    category: "Agent Coding",
    tags: ["terminal", "agentic", "skills", "mcp", "subagents"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Included with Claude Pro/Max, or API per token",
    notes: "What built this hub.",
  },
  {
    name: "Cursor",
    url: "https://cursor.com",
    summary: "The AI-first editor — inline edits plus a repo-wide agent mode.",
    group: "AI",
    category: "Agent Coding",
    tags: ["editor", "agentic", "tab-complete", "multi-model"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier; ~$20/mo Pro",
  },
  {
    name: "Codex",
    url: "https://openai.com/codex",
    summary: "OpenAI's coding agent — CLI, IDE and cloud sandbox runs.",
    group: "AI",
    category: "Agent Coding",
    tags: ["terminal", "agentic", "cloud-sandbox"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Included with ChatGPT plans; API per token",
  },
  {
    name: "Gemini CLI",
    url: "https://github.com/google-gemini/gemini-cli",
    summary: "Google's open-source terminal agent with a large free quota.",
    group: "AI",
    category: "Agent Coding",
    tags: ["terminal", "agentic", "open-source", "free-tier", "mcp"],
    access: "freemium",
    openSource: true,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Generous free daily requests with a Google account",
  },
  {
    name: "Cline",
    url: "https://cline.bot",
    summary: "Open-source VS Code agent — bring your own key, see every diff.",
    group: "AI",
    category: "Agent Coding",
    tags: ["vscode", "open-source", "byok", "mcp", "agentic"],
    access: "free",
    openSource: true,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Extension free; you pay the model provider directly",
  },
  {
    name: "Aider",
    url: "https://aider.chat",
    summary: "Terminal pair programmer with git commits per change.",
    group: "AI",
    category: "Agent Coding",
    tags: ["terminal", "open-source", "git", "byok"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Free tool; you pay the model provider",
  },
  {
    name: "OpenHands",
    url: "https://github.com/All-Hands-AI/OpenHands",
    summary: "Open autonomous dev agent with a sandboxed browser and shell.",
    group: "AI",
    category: "Agent Coding",
    tags: ["open-source", "autonomous", "sandbox", "byok"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "required",
    haveKey: false,
  },
  {
    name: "Windsurf",
    url: "https://windsurf.com",
    summary: "Agentic IDE built around a flow that keeps context between edits.",
    group: "AI",
    category: "Agent Coding",
    tags: ["editor", "agentic", "mcp"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "v0",
    url: "https://v0.app",
    summary: "Vercel's UI generator — prompt to a deployable React app.",
    group: "AI",
    category: "Agent Coding",
    tags: ["ui-generation", "react", "deploy", "prototyping"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },

  // ----- 3D ----------------------------------------------------------------
  {
    name: "Meshy",
    url: "https://www.meshy.ai",
    summary: "Text or image to a textured 3D mesh, game-ready.",
    group: "AI",
    category: "3D",
    tags: ["text-to-3d", "image-to-3d", "texturing", "rigging"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Monthly free credits; paid tiers",
  },
  {
    name: "Tripo",
    url: "https://www.tripo3d.ai",
    summary: "Fast image-to-3D with clean topology and an API.",
    group: "AI",
    category: "3D",
    tags: ["image-to-3d", "fast", "api", "rigging"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Hunyuan3D",
    url: "https://github.com/Tencent-Hunyuan/Hunyuan3D-2",
    summary: "Tencent's open 3D generation models — free weights, runs locally.",
    group: "AI",
    category: "3D",
    tags: ["open-weights", "image-to-3d", "local", "comfyui"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Rodin",
    url: "https://hyper3d.ai",
    summary: "High-fidelity 3D assets aimed at production pipelines.",
    group: "AI",
    category: "3D",
    tags: ["image-to-3d", "high-poly", "pbr"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },

  // ----- Tools -------------------------------------------------------------
  {
    name: "Vercel AI Gateway",
    url: "https://vercel.com/docs/ai-gateway",
    summary: "One key and one API for many providers, with failover and usage stats.",
    group: "AI",
    category: "Tools",
    tags: ["gateway", "multi-provider", "failover", "observability"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Pass-through model cost; free credits to start",
    notes: "The key several apps in this hub read from AI_GATEWAY_API_KEY.",
  },
  {
    name: "OpenRouter",
    url: "https://openrouter.ai",
    summary: "Hundreds of models behind one key, including free-tier variants.",
    group: "AI",
    category: "Tools",
    tags: ["gateway", "multi-provider", "free-models", "byok"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Pay per token; some models genuinely free",
  },
  {
    name: "fal.ai",
    url: "https://fal.ai",
    summary: "Fast hosted inference for image, video and audio models.",
    group: "AI",
    category: "Tools",
    tags: ["inference", "image", "video", "api", "fast"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Per-second GPU billing",
  },
  {
    name: "Replicate",
    url: "https://replicate.com",
    summary: "Run any open model as an API without owning a GPU.",
    group: "AI",
    category: "Tools",
    tags: ["inference", "open-models", "api", "fine-tuning"],
    access: "paid",
    openSource: false,
    hosting: "hosted",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Per-second billing; no subscription",
  },
  {
    name: "Hugging Face",
    url: "https://huggingface.co",
    summary: "Where the open weights live — models, datasets and demo Spaces.",
    group: "AI",
    category: "Tools",
    tags: ["models", "datasets", "spaces", "open-source"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free to browse and download; paid inference and GPU Spaces",
  },
  {
    name: "ComfyUI",
    url: "https://www.comfy.org",
    summary: "Node-graph runner for open image and video models — total control.",
    group: "AI",
    category: "Tools",
    tags: ["open-source", "local", "workflows", "image", "video"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free; needs a GPU",
  },
  {
    name: "Ollama",
    url: "https://ollama.com",
    summary: "One command to run open LLMs locally with an OpenAI-shaped API.",
    group: "AI",
    category: "Tools",
    tags: ["local", "open-source", "llm-runner", "offline"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "LM Studio",
    url: "https://lmstudio.ai",
    summary: "Desktop app for downloading and chatting with local models.",
    group: "AI",
    category: "Tools",
    tags: ["local", "desktop", "llm-runner", "offline"],
    access: "free",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Pinokio",
    url: "https://pinokio.computer",
    summary: "One-click installer and launcher for local AI apps.",
    group: "AI",
    category: "Tools",
    tags: ["local", "installer", "launcher", "open-source"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "n8n",
    url: "https://n8n.io",
    summary: "Self-hostable workflow automation with AI agent nodes.",
    group: "AI",
    category: "Tools",
    tags: ["automation", "workflows", "self-host", "agents"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free self-hosted; paid cloud",
  },

  // ----- Dev ---------------------------------------------------------------
  {
    name: "VS Code",
    url: "https://code.visualstudio.com",
    summary: "The default editor — open source, and the host for most AI coding extensions.",
    group: "Dev",
    category: "Editors",
    tags: ["editor", "extensions", "open-source", "local"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "GitHub",
    url: "https://github.com",
    summary: "Where the code lives — repos, Actions, and the open-source commons.",
    group: "Dev",
    category: "Platforms",
    tags: ["git", "ci", "hosting", "collaboration"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free for public and private repos; paid for org features",
  },
  {
    name: "Vercel",
    url: "https://vercel.com",
    summary: "Push a Next.js app and it is live — plus the AI Gateway several apps here use.",
    group: "Dev",
    category: "Platforms",
    tags: ["hosting", "nextjs", "deploy", "ai-gateway"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Generous hobby tier; Pro from $20/mo",
  },
  {
    name: "Supabase",
    url: "https://supabase.com",
    summary: "Postgres with auth, storage and realtime bolted on — and self-hostable.",
    group: "Dev",
    category: "Backend",
    tags: ["postgres", "auth", "storage", "open-source", "realtime"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "required",
    haveKey: false,
    pricingNote: "Free project tier; Pro from $25/mo; free if self-hosted",
  },
  {
    name: "Docker",
    url: "https://www.docker.com",
    summary: "Runs anything reproducibly — the reason self-hosting is a one-line command.",
    group: "Dev",
    category: "Infra",
    tags: ["containers", "local", "self-host", "open-source"],
    access: "freemium",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free for personal use; paid for larger orgs",
  },
  {
    name: "Cloudflare",
    url: "https://www.cloudflare.com",
    summary: "DNS, tunnels, R2 storage and Workers — the free tier does a lot.",
    group: "Dev",
    category: "Infra",
    tags: ["dns", "cdn", "tunnels", "workers", "storage"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Bruno",
    url: "https://www.usebruno.com",
    summary: "Open-source API client that keeps collections as files in your repo.",
    group: "Dev",
    category: "Utilities",
    tags: ["api-client", "open-source", "local", "git-friendly"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free and offline; no account required",
  },

  // ----- Design ------------------------------------------------------------
  {
    name: "Figma",
    url: "https://www.figma.com",
    summary: "The design file everyone can open — and where handoff actually happens.",
    group: "Design",
    category: "UI Design",
    tags: ["ui", "collaboration", "prototyping", "components"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free for limited files; paid per editor",
  },
  {
    name: "Blender",
    url: "https://www.blender.org",
    summary: "Full 3D suite — modelling, animation, render — free and open source.",
    group: "Design",
    category: "3D",
    tags: ["3d", "animation", "render", "open-source", "local"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free forever, GPL",
  },
  {
    name: "Affinity Designer",
    url: "https://affinity.serif.com",
    summary: "Vector and raster in one app, bought once instead of rented.",
    group: "Design",
    category: "Vector",
    tags: ["vector", "one-time-purchase", "local", "print"],
    access: "paid",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "One-off licence, no subscription",
  },
  {
    name: "Excalidraw",
    url: "https://excalidraw.com",
    summary: "Hand-drawn-looking diagrams in seconds; open source and self-hostable.",
    group: "Design",
    category: "Diagrams",
    tags: ["diagrams", "whiteboard", "open-source", "fast"],
    access: "free",
    openSource: true,
    hosting: "both",
    apiKey: "none",
    haveKey: false,
  },

  // ----- Productivity ------------------------------------------------------
  {
    name: "Obsidian",
    url: "https://obsidian.md",
    summary: "Local markdown notes with backlinks — your files stay yours.",
    group: "Productivity",
    category: "Notes",
    tags: ["markdown", "local", "backlinks", "plugins", "offline"],
    access: "freemium",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free for personal use; paid sync and publish",
  },
  {
    name: "Notion",
    url: "https://www.notion.so",
    summary: "Databases that look like documents — good for shared, structured stuff.",
    group: "Productivity",
    category: "Notes",
    tags: ["database", "wiki", "collaboration", "templates"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
  },
  {
    name: "Raycast",
    url: "https://www.raycast.com",
    summary: "Launcher that swallows half your workflow — scripts, clipboard, snippets.",
    group: "Productivity",
    category: "Launchers",
    tags: ["launcher", "scripts", "clipboard", "extensions"],
    access: "freemium",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free core; Pro adds AI and sync",
  },
  {
    name: "Syncthing",
    url: "https://syncthing.net",
    summary: "Folder sync between your own machines with no cloud in the middle.",
    group: "Productivity",
    category: "Sync",
    tags: ["sync", "p2p", "open-source", "local", "private"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },

  // ----- Media -------------------------------------------------------------
  {
    name: "DaVinci Resolve",
    url: "https://www.blackmagicdesign.com/products/davinciresolve",
    summary: "Professional edit, colour and audio in one app, with a real free version.",
    group: "Media",
    category: "Video Editing",
    tags: ["editing", "color", "audio", "local", "free-tier"],
    access: "freemium",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free version is fully usable; Studio is a one-off licence",
  },
  {
    name: "CapCut",
    url: "https://www.capcut.com",
    summary: "Fast social-format editing with auto-captions that actually work.",
    group: "Media",
    category: "Video Editing",
    tags: ["short-form", "captions", "templates", "fast"],
    access: "freemium",
    openSource: false,
    hosting: "both",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "OBS Studio",
    url: "https://obsproject.com",
    summary: "Screen capture and streaming — the open-source standard.",
    group: "Media",
    category: "Capture",
    tags: ["screen-capture", "streaming", "open-source", "local"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },
  {
    name: "Audacity",
    url: "https://www.audacityteam.org",
    summary: "Quick, free audio editing and cleanup — no project, just a waveform.",
    group: "Media",
    category: "Audio Editing",
    tags: ["audio", "open-source", "local", "cleanup"],
    access: "free",
    openSource: true,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
  },

  // ----- Security ----------------------------------------------------------
  {
    name: "Bitwarden",
    url: "https://bitwarden.com",
    summary: "Password manager that is open source and can be self-hosted.",
    group: "Security",
    category: "Passwords",
    tags: ["passwords", "open-source", "self-host", "2fa"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free tier covers most personal use; $10/yr premium",
  },
  {
    name: "Tailscale",
    url: "https://tailscale.com",
    summary: "Private network between your machines with no port forwarding.",
    group: "Security",
    category: "Networking",
    tags: ["vpn", "wireguard", "remote-access", "free-tier"],
    access: "freemium",
    openSource: true,
    hosting: "both",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free for personal use up to 100 devices",
  },
  {
    name: "Proton VPN",
    url: "https://protonvpn.com",
    summary: "Privacy-first VPN with an unlimited free tier.",
    group: "Security",
    category: "Networking",
    tags: ["vpn", "privacy", "free-tier"],
    access: "freemium",
    openSource: true,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },

  // ----- Trading -----------------------------------------------------------
  {
    name: "MetaTrader 5",
    url: "https://www.metatrader5.com",
    summary: "Where the Expert Advisors run — MQL5, strategy tester, broker terminals.",
    group: "Trading",
    category: "Terminals",
    tags: ["mql5", "expert-advisors", "backtesting", "local"],
    access: "free",
    openSource: false,
    hosting: "self-host",
    apiKey: "none",
    haveKey: false,
    pricingNote: "Free terminal; your broker supplies the account",
  },
  {
    name: "TradingView",
    url: "https://www.tradingview.com",
    summary: "Charting and Pine Script alerts — the analysis half of the workflow.",
    group: "Trading",
    category: "Charting",
    tags: ["charting", "pine-script", "alerts", "screener"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "optional",
    haveKey: false,
    pricingNote: "Free with ads and limits; paid tiers add indicators and alerts",
  },
  {
    name: "MQL5 Market",
    url: "https://www.mql5.com/en/market",
    summary: "Marketplace and forum for EAs, indicators and the MQL5 docs.",
    group: "Trading",
    category: "Marketplaces",
    tags: ["expert-advisors", "indicators", "marketplace", "docs"],
    access: "freemium",
    openSource: false,
    hosting: "hosted",
    apiKey: "none",
    haveKey: false,
  },
];
