import { RealtimeLucy } from "@/components/realtime-lucy/RealtimeLucy";

export const metadata = {
  title: "Realtime Lucy · Ultimate Assistant OS",
  description:
    "Your webcam, re-imagined live by the LingBot-World 2.0 causal world model: every frame is generated by the model, streamed back over WebRTC.",
};

export default function Page() {
  return <RealtimeLucy />;
}
