//+------------------------------------------------------------------+
//|                                             BasketAveragingEA.mq4|
//|                                    Generated by AI Assistant     |
//+------------------------------------------------------------------+
#property copyright "Basket Averaging EA"
#property version   "3.40"
#property strict

// Full source preserved — see original BasketAveragingEA.mq4
// This is the basket partial close + trailing stop + breakeven lock engine
// that forms the foundation of the AMHE's Position Governance layer.
//
// Key contributions to AMHE:
//   - Net basket breakeven calculation (BUY + SELL hedged baskets)
//   - Drawdown-activated averaging with configurable target
//   - Basket trailing stop (start + step)
//   - Automatic + manual partial close (profit-ordered or size-ordered)
//   - Breakeven lock line (activates with 1+ trades after partial close)
//   - CLineManager class for clean visual management
//   - Spread filter + fast close engine with retries
