// ---------------------------------------------------------------------------
// Profile → the AIS-OS Day-1 file set, so a dashboard can be dropped straight
// into a Claude Code folder and become that folder's operating manual.
// Also the reverse: validating a profile JSON made elsewhere (e.g. by the
// ai-os-dashboard skill while onboarding someone in chat) before importing it.
// ---------------------------------------------------------------------------

import { DOMAINS, MECHANISMS } from "./questions";
import { emptyIntake, newProfile, uid } from "./model";
import type { Mechanism, Profile } from "./types";

export interface ExportFile {
  path: string;
  content: string;
}

const or = (s: string, fallback = "_Not answered yet._") => (s.trim() ? s.trim() : fallback);
const mechLabel = (m: Mechanism) => MECHANISMS.find((x) => x.id === m)?.label ?? m;

export function exportFiles(p: Profile): ExportFile[] {
  const i = p.intake;
  const priorities = i.q3.filter((s) => s.trim());
  const firstPriority = priorities[0] ?? "their stated priorities";

  const claude = `# ${p.name}'s AI Operating System

You are ${p.name}'s personal AI OS. Your job is to be their thought partner — help them think, decide, and ship faster on ${firstPriority}.

## Where things live

- \`context/\` — about ${p.name}, their work, their priorities. Read before answering anything about them.
- \`references/voice.md\` — how ${p.name} writes. Match it; never fake it on external content without showing a draft first.
- \`connections.md\` — every system this AI OS can reach, and how.
- \`decisions/log.md\` — append-only record of decisions and why. Suggest logging when a decision is made.
- \`archives/\` — old stuff. Don't delete, move here.

## Knowledge base

${or(i.q1)}

**This quarter:**
${priorities.length ? priorities.map((s, n) => `${n + 1}. ${s}`).join("\n") : "_No priorities set yet._"}

## Connections

${p.connections.map((c) => `- **${c.domain}:** ${c.tool || "—"} (${mechLabel(c.mechanism)})`).join("\n")}

## Capabilities

${p.capabilities.length ? p.capabilities.map((c) => `- \`${c.name}\` — "${c.trigger}" → ${c.output}`).join("\n") : "_None yet. Add one when a task repeats 3+ times._"}

## How you work with me

- Be direct, concise, and clear. Lead with what needs action.
- When I make a decision, suggest logging it in \`decisions/log.md\`.
- When you spot a manual task I'm doing 3+ times, say so.
- Default Shift: for any new task, first ask "to what extent could AI be leveraged here?"

<!-- Generated by New Dashboard from the AIS-OS kit (github.com/nateherkai/AIS-OS, MIT). The Four Cs of an AI OS™ and The Three Ms of AI™ are trademarks of Nate Herk. -->
`;

  const aboutMe = `# About ${p.name}

${or(i.q1)}

## What eats the week

${or(i.q7)}
`;

  const aboutBusiness = `# What ${p.name} does

${or(i.q1)}

## Where money lands

${or(i.q4)}
`;

  const prioritiesMd = `# Priorities — next 90 days

${priorities.length ? priorities.map((s, n) => `${n + 1}. ${p.prioritiesDone.includes(n) ? "~~" + s + "~~ ✓" : s}`).join("\n") : "_Not set yet._"}
`;

  const voice = `# Voice

Match this register when drafting. Don't fake ${p.name}'s voice on external content without showing a draft first.
These are verbatim samples — pasted, not retyped.

## Sample 1

${or(i.q2[0], "_Missing — paste a real email or post._")}

## Sample 2

${or(i.q2[1], "_Missing — paste a real email or post._")}
`;

  const connections = `# Connections

Registry of every system this AI OS can reach. Add a row when a new tool is wired, and save \`references/{tool}-api.md\` at the same time.

| # | Domain | Tool | Mechanism | Last checked |
|---|---|---|---|---|
${p.connections.map((c, n) => `| ${n + 1} | ${c.domain} | ${c.tool || "—"} | ${mechLabel(c.mechanism)} | ${c.lastChecked || "—"} |`).join("\n")}
`;

  const decisions = `# Decisions Log

Append-only. Capture the *why*, not just the *what*.

${p.decisions.length ? [...p.decisions].sort((a, b) => a.date.localeCompare(b.date)).map((d) => `## ${d.date} — ${d.title}\n\n**Decision:** ${d.decision}\n\n**Why:** ${or(d.why, "—")}\n`).join("\n") : "_No decisions logged yet._"}
`;

  const intake = `# AI OS Intake — ${p.name}

## Q1 — Who are you, what do you do, who is it for?
${or(i.q1)}

## Q2 — Voice samples
See references/voice.md.

## Q3 — Priorities (90 days)
${priorities.map((s, n) => `${n + 1}. ${s}`).join("\n") || "_Not answered yet._"}

## Q4 — Where money lands
${or(i.q4)}

## Q5 — Where you talk to people
${or(i.q5)}

## Q6 — Where notes and docs live
${or(i.q6)}

## Q7 — What eats the week / where work is tracked
${or(i.q7)}
`;

  return [
    { path: "CLAUDE.md", content: claude },
    { path: "context/about-me.md", content: aboutMe },
    { path: "context/about-business.md", content: aboutBusiness },
    { path: "context/priorities.md", content: prioritiesMd },
    { path: "references/voice.md", content: voice },
    { path: "connections.md", content: connections },
    { path: "decisions/log.md", content: decisions },
    { path: "aios-intake.md", content: intake },
  ];
}

/** All files in one paste-able document, each under a path header. */
export function bundle(files: ExportFile[]): string {
  return files.map((f) => `<!-- ===== ${f.path} ===== -->\n${f.content}`).join("\n\n");
}

// --- import -----------------------------------------------------------------

const str = (v: unknown, max = 8000) => (typeof v === "string" ? v.slice(0, max) : "");
const arr = (v: unknown): unknown[] => (Array.isArray(v) ? v : []);
const MECH_IDS = new Set(MECHANISMS.map((m) => m.id));

/**
 * Accept a profile JSON from anywhere and return a clean Profile, or null.
 * Unknown fields are dropped; missing ones take defaults; ids are regenerated
 * so importing the same file twice gives two profiles rather than a collision.
 */
export function coerceProfile(raw: unknown): Profile | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const name = str(r.name, 80).trim();
  if (!name) return null;
  const base = newProfile(name);
  const ri = (r.intake ?? {}) as Record<string, unknown>;
  const q2 = arr(ri.q2).map((s) => str(s));
  const q3 = arr(ri.q3).map((s) => str(s, 300));
  const intake = {
    ...emptyIntake(),
    q1: str(ri.q1), q4: str(ri.q4), q5: str(ri.q5), q6: str(ri.q6), q7: str(ri.q7),
    q2: [q2[0] ?? "", q2[1] ?? ""] as [string, string],
    q3: [q3[0] ?? "", q3[1] ?? "", q3[2] ?? ""] as [string, string, string],
  };
  const conns = arr(r.connections) as Record<string, unknown>[];
  return {
    ...base,
    onboarded: r.onboarded === true || Boolean(intake.q1),
    intake,
    connections: DOMAINS.map((domain, n) => {
      const c = conns.find((x) => x && x.domain === domain) ?? conns[n] ?? {};
      const mech = str(c.mechanism) as Mechanism;
      return { domain, tool: str(c.tool, 200), mechanism: MECH_IDS.has(mech) ? mech : "not-connected", lastChecked: str(c.lastChecked, 10) };
    }),
    capabilities: arr(r.capabilities).slice(0, 100).map((c) => {
      const o = (c ?? {}) as Record<string, unknown>;
      return { id: uid(), name: str(o.name, 120), trigger: str(o.trigger, 200), output: str(o.output, 200) };
    }).filter((c) => c.name),
    routines: arr(r.routines).slice(0, 100).map((c) => {
      const o = (c ?? {}) as Record<string, unknown>;
      return { id: uid(), name: str(o.name, 160), schedule: str(o.schedule, 120), lastRun: str(o.lastRun, 10) };
    }).filter((c) => c.name),
    decisions: arr(r.decisions).slice(0, 500).map((c) => {
      const o = (c ?? {}) as Record<string, unknown>;
      return { id: uid(), date: str(o.date, 10), title: str(o.title, 200), decision: str(o.decision, 2000), why: str(o.why, 2000) };
    }).filter((d) => d.title),
  };
}
