"use client";

import { useState } from "react";
import { useStore } from "@/lib/store";
import type { AnalystChanges, AnalystResult, Project } from "@/lib/types";
import { Icon } from "./icons";
import { GhostButton, PrimaryButton } from "./Modal";

const CHANGE_META: {
  key: keyof AnalystChanges;
  label: string;
  dot: string;
}[] = [
  { key: "features_added", label: "New Features", dot: "bg-core" },
  { key: "features_changed", label: "Feature Changes", dot: "bg-amber-400" },
  { key: "improvements", label: "Improvements", dot: "bg-support" },
  { key: "bug_fixes", label: "Bug Fixes", dot: "bg-red-400" },
  { key: "missing_documentation", label: "Missing Documentation", dot: "bg-violet-400" },
];

export function AIPanel({ project }: { project: Project }) {
  const applyAnalystResult = useStore((s) => s.applyAnalystResult);
  const [loading, setLoading] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<AnalystResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const regenerate = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch("/api/regenerate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ project }),
      });
      if (!res.ok) throw new Error(`Analysis failed (${res.status})`);
      setResult((await res.json()) as AnalystResult);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Analysis failed");
    } finally {
      setLoading(false);
    }
  };

  const apply = async () => {
    if (!result) return;
    setApplying(true);
    await applyAnalystResult(project.id, result);
    setApplying(false);
    setResult(null);
  };

  const hasChanges =
    result && CHANGE_META.some((c) => (result.changes[c.key] ?? []).length > 0);

  return (
    <section className="overflow-hidden rounded-2xl border border-brand/30 bg-gradient-to-b from-brand/[0.10] to-panel">
      <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand/20 text-brand">
            <Icon.Sparkles width={20} height={20} />
          </div>
          <div>
            <h2 className="text-base font-semibold text-ink">AI Project Analyst</h2>
            <p className="mt-0.5 max-w-md text-xs text-ink-muted">
              Reads the Knowledge Inbox, versions, files and existing features, then rewrites the
              project&apos;s summary, basic overview, detailed explanation and core/supporting
              feature lists — and tells you what changed. Nothing you captured is lost.
            </p>
          </div>
        </div>
        <PrimaryButton onClick={regenerate} disabled={loading || applying}>
          <Icon.Sparkles width={16} height={16} className={loading ? "animate-spin" : ""} />
          {loading ? "Analyzing…" : "Regenerate Project"}
        </PrimaryButton>
      </div>

      {error && (
        <div className="mx-5 mb-5 rounded-xl border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-300">
          {error}
        </div>
      )}

      {result && (
        <div className="animate-fade-in border-t border-brand/20 bg-panel/60 p-5">
          <div className="mb-4 flex items-center gap-2">
            <span className="rounded-full bg-panel-2 px-2.5 py-1 text-[11px] font-medium text-ink-muted">
              {result.engine === "ai" ? "✦ Generated by AI model" : "✦ Heuristic analysis"}
            </span>
            <span className="text-[11px] text-ink-faint">Review, then apply.</span>
          </div>

          {/* Change detection */}
          <div className="mb-5">
            <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-ink-faint">
              Change Detection
            </h3>
            {hasChanges ? (
              <div className="grid gap-3 sm:grid-cols-2">
                {CHANGE_META.map(({ key, label, dot }) => {
                  const items = result.changes[key] ?? [];
                  if (!items.length) return null;
                  return (
                    <div key={key} className="rounded-xl border border-line bg-canvas p-3">
                      <div className="mb-1.5 flex items-center gap-2">
                        <span className={`h-2 w-2 rounded-full ${dot}`} />
                        <span className="text-xs font-semibold text-ink">{label}</span>
                      </div>
                      <ul className="space-y-1">
                        {items.map((it, i) => (
                          <li key={i} className="text-xs leading-snug text-ink-muted">
                            • {it}
                          </li>
                        ))}
                      </ul>
                    </div>
                  );
                })}
              </div>
            ) : (
              <p className="text-xs text-ink-faint">
                No new changes detected from the current knowledge.
              </p>
            )}
          </div>

          {/* Proposed documentation */}
          <div className="mb-5 space-y-3">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-ink-faint">
              Proposed Documentation
            </h3>
            <Diff label="One-Line Summary" before={project.one_liner} after={result.one_liner} />
            <Diff label="Overview" before={project.overview} after={result.overview} multiline />
            <Diff
              label="Detailed Explanation"
              before={project.detailed ?? ""}
              after={result.detailed}
              multiline
              scroll
            />
            <ProposedFeatures result={result} />
          </div>

          <div className="flex items-center justify-end gap-2">
            <GhostButton onClick={() => setResult(null)} disabled={applying}>
              Discard
            </GhostButton>
            <PrimaryButton onClick={apply} disabled={applying}>
              <Icon.Check width={16} height={16} />
              {applying ? "Applying…" : "Apply to Project"}
            </PrimaryButton>
          </div>
        </div>
      )}
    </section>
  );
}

function Diff({
  label,
  before,
  after,
  multiline,
  scroll,
}: {
  label: string;
  before: string;
  after: string;
  multiline?: boolean;
  scroll?: boolean;
}) {
  const changed = before.trim() !== after.trim();
  return (
    <div className="rounded-xl border border-line bg-canvas p-3">
      <div className="mb-1.5 flex items-center gap-2">
        <span className="text-xs font-semibold text-ink">{label}</span>
        {changed ? (
          <span className="rounded-full bg-brand/15 px-1.5 py-0.5 text-[10px] font-medium text-brand">
            updated
          </span>
        ) : (
          <span className="text-[10px] text-ink-faint">unchanged</span>
        )}
      </div>
      <p
        className={
          `text-sm text-ink ${multiline ? "leading-relaxed whitespace-pre-wrap" : ""} ` +
          (scroll ? "max-h-64 overflow-y-auto" : "")
        }
      >
        {after || "—"}
      </p>
    </div>
  );
}

function ProposedFeatures({ result }: { result: AnalystResult }) {
  return (
    <div className="grid gap-3 sm:grid-cols-2">
      <div className="rounded-xl border border-core/30 bg-core/[0.06] p-3">
        <div className="mb-2 flex items-center gap-2">
          <span className="h-2 w-2 rounded-full bg-core" />
          <span className="text-xs font-semibold text-ink">Core Features</span>
          <span className="text-[10px] text-ink-faint">{result.core_features.length}</span>
        </div>
        <ul className="space-y-1">
          {result.core_features.map((f, i) => (
            <li key={i} className="text-xs text-ink-muted">
              • {f.title}
            </li>
          ))}
        </ul>
      </div>
      <div className="rounded-xl border border-support/30 bg-support/[0.06] p-3">
        <div className="mb-2 flex items-center gap-2">
          <span className="h-2 w-2 rounded-full bg-support" />
          <span className="text-xs font-semibold text-ink">Supporting Features</span>
          <span className="text-[10px] text-ink-faint">{result.supporting_features.length}</span>
        </div>
        <ul className="space-y-1">
          {result.supporting_features.map((f, i) => (
            <li key={i} className="text-xs text-ink-muted">
              • {f.title}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
