import { describe, expect, it } from "vitest";
import type { Folder, Item } from "@/lib/recall/types";
import {
  APP_VALUE,
  buildPlan,
  cleanName,
  folderListText,
  hashText,
  type DriveEntry,
} from "./plan";

const NOW = "2026-09-13T00:00:00.000Z";

const folder = (id: string, name: string, parentId: string | null, extra: Partial<Folder> = {}) =>
  ({ id, name, parentId, autoGenerated: false, createdAt: NOW, ...extra }) as Folder;

const item = (over: Partial<Item>) =>
  ({
    id: "i1",
    title: "Title",
    body: "",
    summary: "",
    kind: "note",
    source: "manual",
    folderId: null,
    tags: [],
    createdAt: NOW,
    updatedAt: NOW,
    ...over,
  }) as Item;

const photos = folder("p", "Photos", null, { role: "photos" });

describe("buildPlan — the Drive layout", () => {
  it("starts with Ultimate Assistant OS, holding Photos and Folders", () => {
    const plan = buildPlan([], [], []);
    expect(plan.folders.slice(0, 3).map((f) => [f.key, f.name, f.parentKey])).toEqual([
      ["root", "Ultimate Assistant OS", null],
      ["photos", "Photos", "root"],
      ["folders", "Folders", "root"],
    ]);
  });

  it("puts photo albums under Photos, not as a second Photos folder", () => {
    const plan = buildPlan([photos, folder("a", "My Little Family", "p")], [], []);
    expect(plan.folders.find((f) => f.key === "folder:a")?.parentKey).toBe("photos");
    expect(plan.folders.some((f) => f.key === "folder:p")).toBe(false);
  });

  it("puts ordinary folders under Folders, nested as they are in the app", () => {
    const plan = buildPlan([folder("t", "trading fx", null), folder("v", "vps 2026", "t")], [], []);
    expect(plan.folders.find((f) => f.key === "folder:t")?.parentKey).toBe("folders");
    expect(plan.folders.find((f) => f.key === "folder:v")?.parentKey).toBe("folder:t");
  });

  it("always lists a parent before its child", () => {
    const plan = buildPlan([folder("c", "child", "b"), folder("b", "mid", "a"), folder("a", "top", null)], [], []);
    const order = plan.folders.map((f) => f.key);
    expect(order.indexOf("folder:a")).toBeLessThan(order.indexOf("folder:b"));
    expect(order.indexOf("folder:b")).toBeLessThan(order.indexOf("folder:c"));
  });
});

describe("buildPlan — what becomes a file", () => {
  it("turns a note into a document inside its folder", () => {
    const plan = buildPlan([folder("t", "trading fx", null)], [item({ folderId: "t", body: "buy low" })], []);
    const f = plan.files[0];
    expect(f.parentKey).toBe("folder:t");
    expect(f.source).toEqual({ type: "doc", text: "Title\n\nbuy low" });
    expect(f.version).toBe(NOW);
  });

  it("uploads a stored photo as the real file, by its file name", () => {
    const plan = buildPlan(
      [photos],
      [item({ kind: "image", folderId: "p", attachment: { name: "IMG_1.jpg", type: "image/jpeg", size: 1, fileId: "blob_1" } })],
      [],
    );
    expect(plan.files[0]).toMatchObject({
      name: "IMG_1.jpg",
      parentKey: "photos",
      source: { type: "blob", fileId: "blob_1", mime: "image/jpeg" },
    });
  });

  it("reports an image with no stored file instead of silently skipping it", () => {
    const plan = buildPlan([], [item({ kind: "image", title: "old pic" })], []);
    expect(plan.files).toHaveLength(0);
    expect(plan.notBackedUp[0].title).toBe("old pic");
  });

  it("puts items in no folder into Unfiled, and makes Unfiled only when needed", () => {
    expect(buildPlan([], [], []).folders.some((f) => f.key === "unfiled")).toBe(false);
    const plan = buildPlan([], [item({})], []);
    expect(plan.folders.find((f) => f.key === "unfiled")?.parentKey).toBe("folders");
    expect(plan.files[0].parentKey).toBe("unfiled");
  });

  it("still backs up an item whose folder no longer exists, in Unfiled", () => {
    const plan = buildPlan([], [item({ folderId: "gone" })], []);
    expect(plan.files[0].parentKey).toBe("unfiled");
  });

  it("gathers a folder's links, to-dos and logins into one list document", () => {
    const plan = buildPlan(
      [folder("t", "trading fx", null)],
      [
        item({ id: "l", kind: "link", title: "Broker", url: "https://x.com", folderId: "t" }),
        item({ id: "d", kind: "todo", title: "Renew VPS", done: true, folderId: "t" }),
      ],
      [],
    );
    expect(plan.files).toHaveLength(1);
    expect(plan.files[0]).toMatchObject({ name: "Links, to-dos & logins", parentKey: "folder:t" });
  });
});

describe("passwords never leave the device", () => {
  const login = item({
    id: "c",
    kind: "credential",
    title: "Coinexx",
    url: "https://coinexx.com",
    password: "hunter2-SECRET",
    fields: { username: "jack", password: "also-SECRET", apiKey: "key-SECRET", pin: "9999" },
  });

  it("lists the site and username", () => {
    const text = folderListText([login]);
    expect(text).toContain("Coinexx");
    expect(text).toContain("https://coinexx.com");
    expect(text).toContain("username: jack");
  });

  it("never includes the password, or any field that looks like a secret", () => {
    const text = folderListText([login]);
    expect(text).not.toContain("hunter2");
    expect(text).not.toMatch(/SECRET/);
    expect(text).not.toContain("9999");
  });

  it("never makes a file of its own for a login", () => {
    const plan = buildPlan([], [login], []);
    expect(plan.files.every((f) => f.key.startsWith("list:"))).toBe(true);
    expect(JSON.stringify(plan)).not.toMatch(/SECRET|hunter2/);
  });
});

describe("matching what is already on Drive", () => {
  const onDrive = (key: string, version: string, app = APP_VALUE): DriveEntry => ({
    id: "d1",
    name: "x",
    parents: ["p1"],
    appProperties: { dashboardApp: app, dashboardKey: key, dashboardVersion: version },
  });

  it("marks an unchanged file as unchanged", () => {
    const plan = buildPlan([], [item({ id: "n" })], [onDrive("item:n", NOW)]);
    expect(plan.files[0].changed).toBe(false);
    expect(plan.files[0].existing?.id).toBe("d1");
  });

  it("marks an edited file as changed", () => {
    const plan = buildPlan([], [item({ id: "n" })], [onDrive("item:n", "older")]);
    expect(plan.files[0].changed).toBe(true);
  });

  it("ignores Drive files that belong to something else", () => {
    const plan = buildPlan([], [item({ id: "n" })], [onDrive("item:n", NOW, "other-app")]);
    expect(plan.files[0].existing).toBeUndefined();
  });

  // The user chose a backup that never deletes.
  it("has no step at all for something deleted in Dashboard", () => {
    const plan = buildPlan([], [], [onDrive("item:deleted", NOW)]);
    expect(plan.files).toHaveLength(0);
  });
});

describe("helpers", () => {
  it("makes names safe for Drive", () => {
    expect(cleanName("a/b\\c   d")).toBe("a-b-c d");
    expect(cleanName("   ")).toBe("Untitled");
  });

  it("gives the same text the same fingerprint, and different text a different one", () => {
    expect(hashText("abc")).toBe(hashText("abc"));
    expect(hashText("abc")).not.toBe(hashText("abd"));
  });
});
