// ---------------------------------------------------------------------------
// Recall — first-run seed content.
// A small, life-wide starter set (game dev, AI models, cooking, restaurants)
// so the app opens alive and the search/agent have something to work with.
// ---------------------------------------------------------------------------

import { nowIso, uid } from "../utils";
import type { Folder, Item, RecallData } from "./types";

export function buildSeed(): RecallData {
  const ts = nowIso();
  const folder = (name: string, parentId: string | null): Folder => ({
    id: uid("fld"),
    name,
    parentId,
    autoGenerated: false,
    createdAt: ts,
  });

  const inbox = folder("Inbox", null);
  const gameDev = folder("Game Dev", null);
  const engines = folder("Engines", gameDev.id);
  const ai = folder("AI & Models", null);
  const videoModels = folder("Video Models", ai.id);
  const cooking = folder("Cooking", null);
  const restaurants = folder("Restaurants", null);

  const folders = [inbox, gameDev, engines, ai, videoModels, cooking, restaurants];

  const item = (
    partial: Omit<Item, "id" | "createdAt" | "updatedAt" | "source" | "kind"> &
      Partial<Pick<Item, "kind" | "source">>,
  ): Item => ({
    id: uid("itm"),
    kind: "note",
    source: "manual",
    createdAt: ts,
    updatedAt: ts,
    ...partial,
  });

  const items: Item[] = [
    item({
      title: "Leaning toward Unity over Unreal",
      body:
        "Reconsidering the engine choice for the next game. Unity's C# workflow and asset store fit a small solo project better than Unreal's C++/Blueprints for what I'm building. Unreal still wins on out-of-the-box visual fidelity. Decision: prototype in Unity first.",
      summary: "Why Unity beats Unreal for a small solo game project — decision to prototype in Unity.",
      folderId: engines.id,
      tags: ["unity", "unreal", "game-dev", "engines"],
    }),
    item({
      title: "Open-source video models to track",
      body:
        "Newest open / open-weight text-to-video models worth watching: Seedance 2, Hunyuan Video, Wan 2.x, and Mochi. Tracking quality, license, and whether they run on a single consumer GPU. Seedance 2 is the current front-runner for prompt adherence.",
      summary: "A running shortlist of the newest open text-to-video models and what to evaluate.",
      folderId: videoModels.id,
      tags: ["video-model", "seedance", "open-source", "ai"],
    }),
    item({
      title: "Open-weight LLM shortlist",
      body:
        "LLMs to keep an eye on for local + gateway use: Qwen, Llama, Mistral, and the newest Claude/Gemini via the gateway. Note context windows and tool-calling quality when picking one for the agent.",
      summary: "Which open-weight and gateway LLMs to consider, with context + tool-calling notes.",
      folderId: ai.id,
      tags: ["llm", "open-source", "ai"],
    }),
    item({
      title: "Weeknight garlic butter pasta",
      body:
        "Fast 15-minute dinner. Cook spaghetti; meanwhile melt butter with lots of minced garlic and chili flakes, add a ladle of pasta water, toss with parmesan and parsley. Finish with lemon. Scales easily for 2–4.",
      summary: "A 15-minute garlic butter pasta recipe that scales for 2–4.",
      folderId: cooking.id,
      tags: ["recipe", "pasta", "cooking", "quick"],
    }),
    item({
      title: "Aria — Italian, worth a return",
      body:
        "Cozy neighborhood Italian spot. The cacio e pepe and the tiramisu were standouts; service was quick. Good for a low-key date night. Book ahead on weekends.",
      summary: "Neighborhood Italian restaurant — great cacio e pepe + tiramisu, book weekends.",
      folderId: restaurants.id,
      tags: ["restaurant", "italian", "date-night"],
    }),
  ];

  return { folders, items };
}
