// ---------------------------------------------------------------------------
// Recall — local-first data access.
// Backed by localStorage today; the async-friendly, folder+item shape maps
// cleanly onto a Supabase (+ pgvector) backend later without touching the UI.
// All mutators return the fresh RecallData so the component can setData(result).
// ---------------------------------------------------------------------------

import { saveSynced } from "@/lib/sync/appState";
import { nowIso, uid } from "../utils";
import { buildSeed } from "./seed";
import type { AgentAction, Cipher, Folder, Item, RecallData, SectionId } from "./types";
import { PHOTOS_ROOT } from "./photos/types";
import * as calendar from "./calendar/store";
import { createPerson } from "./photos/store";
import { scopedKey } from "@/lib/sync/identity";

/** Also the app_state sync key; the component passes it to useRemotePull. */
export const KEY = "recall:v1";

// ----- persistence ---------------------------------------------------------

function load(): RecallData {
  if (typeof window === "undefined") return { folders: [], items: [] };
  try {
    const raw = window.localStorage.getItem(scopedKey(KEY));
    if (!raw) {
      const seeded = buildSeed();
      save(seeded);
      return seeded;
    }
    const data = JSON.parse(raw) as RecallData;
    return {
      folders: Array.isArray(data.folders) ? data.folders : [],
      items: Array.isArray(data.items) ? data.items : [],
    };
  } catch {
    return buildSeed();
  }
}

function save(data: RecallData): void {
  // Local write plus, when signed in, a push to app_state so folders and items
  // are the same on every device the user opens Recall on.
  saveSynced(KEY, data);
}

export function getData(): RecallData {
  return load();
}

/** v1 is always local; the badge flips when a cloud backend is wired in. */
export function isLocal(): boolean {
  return true;
}

// ----- helpers -------------------------------------------------------------

export function folderPathString(folders: Folder[], folderId: string | null): string {
  if (!folderId) return "Inbox";
  const byId = new Map(folders.map((f) => [f.id, f]));
  const parts: string[] = [];
  let cur = byId.get(folderId);
  const guard = new Set<string>();
  while (cur && !guard.has(cur.id)) {
    guard.add(cur.id);
    parts.unshift(cur.name);
    cur = cur.parentId ? byId.get(cur.parentId) : undefined;
  }
  return parts.join(" › ") || "Inbox";
}

export function allTags(data: RecallData): string[] {
  const set = new Set<string>();
  for (const item of data.items) for (const t of item.tags) set.add(t);
  return [...set].sort((a, b) => a.localeCompare(b));
}

export function childFolders(folders: Folder[], parentId: string | null): Folder[] {
  return folders
    .filter((f) => f.parentId === parentId)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Every folder id under (and including) a given folder. */
export function descendantFolderIds(folders: Folder[], rootId: string): Set<string> {
  const out = new Set<string>([rootId]);
  let added = true;
  while (added) {
    added = false;
    for (const f of folders) {
      if (f.parentId && out.has(f.parentId) && !out.has(f.id)) {
        out.add(f.id);
        added = true;
      }
    }
  }
  return out;
}

/** Create the folders along a path (reusing matches case-insensitively). */
function ensurePath(data: RecallData, path: string[], auto: boolean): string | null {
  let parentId: string | null = null;
  for (const rawName of path) {
    const name = rawName.trim();
    if (!name) continue;
    const existing = data.folders.find(
      (f) => f.parentId === parentId && f.name.trim().toLowerCase() === name.toLowerCase(),
    );
    if (existing) {
      parentId = existing.id;
    } else {
      const created: Folder = {
        id: uid("fld"),
        name,
        parentId,
        autoGenerated: auto,
        // A top-level "Photos" is the camera-roll root wherever it gets created
        // from — the review queue, the agent, or the user typing the path by
        // hand — so the marking happens here rather than at one call site.
        role: parentId === null && name.toLowerCase() === PHOTOS_ROOT.toLowerCase() ? "photos" : undefined,
        icon: parentId === null && name.toLowerCase() === PHOTOS_ROOT.toLowerCase() ? "image" : undefined,
        createdAt: nowIso(),
      };
      data.folders.push(created);
      parentId = created.id;
    }
  }
  return parentId;
}

export function ensureFolderPath(path: string[], auto = true): { data: RecallData; folderId: string | null } {
  const data = load();
  const folderId = ensurePath(data, path, auto);
  save(data);
  return { data, folderId };
}

/** The managed Photos root, if it exists yet. */
export function photosRoot(folders: Folder[]): Folder | null {
  return (
    folders.find((f) => f.parentId === null && f.role === "photos") ??
    folders.find((f) => f.parentId === null && f.name.toLowerCase() === PHOTOS_ROOT.toLowerCase()) ??
    null
  );
}

/** Find or create the Photos root and return the fresh data alongside it. */
export function ensurePhotosRoot(): { data: RecallData; folderId: string | null } {
  return ensureFolderPath([PHOTOS_ROOT], false);
}

// ----- folder mutations ----------------------------------------------------

export interface FolderInput {
  name: string;
  description?: string;
  icon?: string;
}

/** Turn a section on for a folder. */
export function addFolderSection(id: string, section: SectionId): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === id);
  if (f) {
    const next = new Set(f.sections ?? []);
    next.add(section);
    f.sections = [...next];
  }
  save(data);
  return data;
}

/**
 * Turn a section off. Only ever called for an empty section — the workspace
 * keeps rendering any section that holds items regardless of this list.
 */
export function removeFolderSection(id: string, section: SectionId): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === id);
  if (f) f.sections = (f.sections ?? []).filter((s) => s !== section);
  save(data);
  return data;
}

export function createFolder(
  input: string | FolderInput,
  parentId: string | null,
  accent?: string,
): { data: RecallData; folder: Folder } {
  const spec = typeof input === "string" ? { name: input } : input;
  const data = load();
  const folder: Folder = {
    id: uid("fld"),
    name: spec.name.trim() || "Untitled",
    parentId,
    autoGenerated: false,
    description: spec.description?.trim() || undefined,
    icon: spec.icon,
    accent,
    createdAt: nowIso(),
  };
  data.folders.push(folder);
  save(data);
  return { data, folder };
}

export function renameFolder(id: string, name: string): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === id);
  if (f) f.name = name.trim() || f.name;
  save(data);
  return data;
}

/** Edit the presentation of a folder — name, blurb, tile icon. */
export function updateFolder(id: string, patch: FolderInput): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === id);
  if (f) {
    if (patch.name?.trim()) f.name = patch.name.trim();
    f.description = patch.description?.trim() || undefined;
    if (patch.icon !== undefined) f.icon = patch.icon;
  }
  save(data);
  return data;
}

/** Delete a folder; its child folders and items lift up to its parent. */
export function deleteFolder(id: string): RecallData {
  const data = load();
  const target = data.folders.find((f) => f.id === id);
  if (!target) return data;
  const parentId = target.parentId;
  for (const f of data.folders) if (f.parentId === id) f.parentId = parentId;
  for (const it of data.items) if (it.folderId === id) it.folderId = parentId;
  data.folders = data.folders.filter((f) => f.id !== id);
  save(data);
  return data;
}

// ----- item mutations ------------------------------------------------------

export interface NewItemInput {
  title: string;
  body: string;
  summary: string;
  kind: Item["kind"];
  source: Item["source"];
  folderId: string | null;
  tags: string[];
  url?: string | null;
  attachment?: Item["attachment"];
  driveId?: string | null;
  done?: boolean;
  fields?: Record<string, string>;
  secret?: Cipher | null;
  extract?: string;
  extractStatus?: Item["extractStatus"];
  /** Person ids recognised in a photo. */
  people?: string[];
  photoCategoryId?: string | null;
  driveBackupId?: string | null;
}

export function createItem(input: NewItemInput): { data: RecallData; item: Item } {
  const data = load();
  const ts = nowIso();
  const item: Item = {
    id: uid("itm"),
    title: input.title.trim() || "Untitled",
    body: input.body,
    summary: input.summary,
    kind: input.kind,
    source: input.source,
    folderId: input.folderId,
    tags: dedupeTags(input.tags),
    url: input.url ?? null,
    attachment: input.attachment ?? null,
    driveId: input.driveId ?? null,
    done: input.done ?? false,
    fields: input.fields ?? {},
    secret: input.secret ?? null,
    extract: input.extract,
    extractStatus: input.extractStatus,
    people: input.people,
    photoCategoryId: input.photoCategoryId ?? null,
    driveBackupId: input.driveBackupId ?? null,
    createdAt: ts,
    updatedAt: ts,
  };
  data.items.push(item);
  save(data);
  return { data, item };
}

export function updateItem(id: string, patch: Partial<Omit<Item, "id" | "createdAt">>): RecallData {
  const data = load();
  const it = data.items.find((x) => x.id === id);
  if (it) {
    Object.assign(it, patch);
    if (patch.tags) it.tags = dedupeTags(patch.tags);
    it.updatedAt = nowIso();
  }
  save(data);
  return data;
}

export function deleteItem(id: string): RecallData {
  const data = load();
  data.items = data.items.filter((x) => x.id !== id);
  save(data);
  return data;
}

export function moveItem(itemId: string, folderId: string | null): RecallData {
  return updateItem(itemId, { folderId });
}

export function setItemTags(itemId: string, tags: string[]): RecallData {
  return updateItem(itemId, { tags: dedupeTags(tags) });
}

function dedupeTags(tags: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of tags) {
    const t = raw.toLowerCase().trim().replace(/\s+/g, "-");
    if (t && !seen.has(t)) {
      seen.add(t);
      out.push(t);
    }
  }
  return out.slice(0, 12);
}

// ----- typed-record mutations ---------------------------------------------

export function toggleTodo(itemId: string): RecallData {
  const data = load();
  const it = data.items.find((x) => x.id === itemId);
  if (it) {
    it.done = !it.done;
    it.updatedAt = nowIso();
  }
  save(data);
  return data;
}

/** Merge structured fields; an empty string clears a key. */
export function setItemFields(itemId: string, patch: Record<string, string>): RecallData {
  const data = load();
  const it = data.items.find((x) => x.id === itemId);
  if (it) {
    const next = { ...(it.fields ?? {}) };
    for (const [k, v] of Object.entries(patch)) {
      if (v === "") delete next[k];
      else next[k] = v;
    }
    it.fields = next;
    it.updatedAt = nowIso();
  }
  save(data);
  return data;
}

/** Store (or clear) the one encrypted value on a credential. */
export function setItemSecret(itemId: string, secret: Cipher | null): RecallData {
  const data = load();
  const it = data.items.find((x) => x.id === itemId);
  if (it) {
    it.secret = secret;
    it.updatedAt = nowIso();
  }
  save(data);
  return data;
}

export function renameItem(itemId: string, title: string): RecallData {
  return updateItem(itemId, { title: title.trim() || "Untitled" });
}

/** Every credential ciphertext — used when re-keying the vault. */
export function allSecrets(): { id: string; cipher: Cipher }[] {
  return load()
    .items.filter((i) => i.secret)
    .map((i) => ({ id: i.id, cipher: i.secret as Cipher }));
}

export function applyRekeyedSecrets(next: { id: string; cipher: Cipher }[]): RecallData {
  const data = load();
  const byId = new Map(next.map((n) => [n.id, n.cipher]));
  for (const it of data.items) {
    const c = byId.get(it.id);
    if (c) it.secret = c;
  }
  save(data);
  return data;
}

/** Drop every stored ciphertext — pairs with destroying the vault. */
export function clearAllSecrets(): RecallData {
  const data = load();
  for (const it of data.items) if (it.secret) it.secret = null;
  save(data);
  return data;
}

// ----- migration -----------------------------------------------------------

const MIGRATION_FLAG = "recall:migrated:websites:v1";

/**
 * Earlier builds had separate "server" and "site" kinds. They are one thing —
 * a website — so fold them together. Runs once, keeps every field.
 */
export function migrateRecords(): RecallData {
  const data = load();
  if (typeof window === "undefined") return data;
  if (window.localStorage.getItem(scopedKey(MIGRATION_FLAG))) return data;
  window.localStorage.setItem(scopedKey(MIGRATION_FLAG), nowIso());

  let touched = false;
  for (const it of data.items) {
    const kind = it.kind as string;
    if (kind === "server" || kind === "site") {
      it.kind = "website";
      const f = { ...(it.fields ?? {}) };
      // "domain" was the site-side name for the same field.
      if (f.domain && !f.url) {
        f.url = f.domain;
        delete f.domain;
      }
      it.fields = f;
      it.tags = dedupeTags([...it.tags.filter((t) => t !== "server" && t !== "site"), "website"]);
      touched = true;
    }
  }
  if (touched) save(data);
  return data;
}

// ----- folder structure operations ----------------------------------------

/** True when `candidateParent` sits inside `folderId` (or is it). */
function wouldCycle(folders: Folder[], folderId: string, candidateParent: string | null): boolean {
  let cur = candidateParent;
  const guard = new Set<string>();
  while (cur && !guard.has(cur)) {
    if (cur === folderId) return true;
    guard.add(cur);
    cur = folders.find((f) => f.id === cur)?.parentId ?? null;
  }
  return false;
}

/** Reparent a folder (with everything under it). No-ops on a cycle. */
export function moveFolder(folderId: string, parentId: string | null): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === folderId);
  if (!f || wouldCycle(data.folders, folderId, parentId)) return data;
  f.parentId = parentId;
  save(data);
  return data;
}

/**
 * Fold `sourceId` into `targetId`: its items and sub-folders move across, then
 * the now-empty source folder is removed. Nothing is deleted.
 */
export function mergeFolders(sourceId: string, targetId: string | null): RecallData {
  const data = load();
  const source = data.folders.find((f) => f.id === sourceId);
  if (!source || sourceId === targetId) return data;
  if (targetId && wouldCycle(data.folders, sourceId, targetId)) return data;

  for (const it of data.items) if (it.folderId === sourceId) it.folderId = targetId;
  for (const f of data.folders) if (f.parentId === sourceId) f.parentId = targetId;
  data.folders = data.folders.filter((f) => f.id !== sourceId);
  save(data);
  return data;
}

// ----- agent action execution ---------------------------------------------

function pathLabel(path: string[]): string {
  return path.join(" › ") || "Inbox";
}

/**
 * Apply an agent-proposed action locally. Returns fresh data + a human note.
 * Nothing here runs without the user confirming it in the chat first.
 */
export interface ActionResult {
  data: RecallData;
  note: string;
  /** Set when the action wrote to a store the caller must also re-read. */
  calendarChanged?: boolean;
  photosChanged?: boolean;
}

export function executeAction(action: AgentAction): ActionResult {
  switch (action.type) {
    case "create_folder": {
      const { data } = ensureFolderPath(action.path, false);
      return { data, note: `Created folder ${pathLabel(action.path)}` };
    }

    case "move_item": {
      const { folderId } = ensureFolderPath(action.path, true);
      const data = moveItem(action.itemId, folderId);
      const it = data.items.find((x) => x.id === action.itemId);
      return { data, note: `Moved “${it?.title ?? "item"}” to ${pathLabel(action.path)}` };
    }

    case "move_items": {
      const { folderId } = ensureFolderPath(action.path, true);
      let data = load();
      let moved = 0;
      for (const id of action.itemIds) {
        if (data.items.some((x) => x.id === id)) {
          data = moveItem(id, folderId);
          moved++;
        }
      }
      return { data, note: `Moved ${moved} ${moved === 1 ? "item" : "items"} to ${pathLabel(action.path)}` };
    }

    case "add_tags": {
      const data = load();
      const it = data.items.find((x) => x.id === action.itemId);
      if (!it) return { data, note: "Item not found" };
      const next = setItemTags(action.itemId, [...it.tags, ...action.tags]);
      return { data: next, note: `Tagged “${it.title}” with ${action.tags.join(", ")}` };
    }

    case "remove_tags": {
      const data = load();
      const it = data.items.find((x) => x.id === action.itemId);
      if (!it) return { data, note: "Item not found" };
      const drop = action.tags.map((x) => x.toLowerCase());
      const next = setItemTags(
        action.itemId,
        it.tags.filter((t) => !drop.includes(t.toLowerCase())),
      );
      return { data: next, note: `Removed ${action.tags.join(", ")} from “${it.title}”` };
    }

    case "create_note": {
      const { folderId } = ensureFolderPath(action.path, true);
      const { data, item } = createItem({
        title: action.title,
        body: action.body,
        summary: action.body.slice(0, 160),
        kind: "note",
        source: "manual",
        folderId,
        tags: action.tags,
      });
      return { data, note: `Created note “${item.title}”` };
    }

    case "rename_item": {
      const data = updateItem(action.itemId, { title: action.title.trim() || "Untitled" });
      return { data, note: `Renamed to “${action.title}”` };
    }

    case "edit_note": {
      const before = load().items.find((x) => x.id === action.itemId);
      if (!before) return { data: load(), note: "Item not found" };
      const data = updateItem(action.itemId, { body: action.body });
      return { data, note: `Rewrote the body of “${before.title}”` };
    }

    case "rename_folder": {
      const data = renameFolder(action.folderId, action.name);
      return { data, note: `Renamed folder to “${action.name}”` };
    }

    case "move_folder": {
      const target = action.path.length ? ensureFolderPath(action.path, true).folderId : null;
      const data = moveFolder(action.folderId, target);
      const f = data.folders.find((x) => x.id === action.folderId);
      return { data, note: `Moved folder “${f?.name ?? ""}” to ${pathLabel(action.path)}` };
    }

    case "merge_folders": {
      const source = load().folders.find((f) => f.id === action.sourceId);
      const target = action.targetPath.length
        ? ensureFolderPath(action.targetPath, true).folderId
        : null;
      const data = mergeFolders(action.sourceId, target);
      return {
        data,
        note: `Merged “${source?.name ?? "folder"}” into ${pathLabel(action.targetPath)}`,
      };
    }

    case "delete_item": {
      const it = load().items.find((x) => x.id === action.itemId);
      const data = deleteItem(action.itemId);
      return { data, note: `Deleted “${it?.title ?? "item"}”` };
    }

    case "delete_folder": {
      const f = load().folders.find((x) => x.id === action.folderId);
      const data = deleteFolder(action.folderId);
      return { data, note: `Deleted folder “${f?.name ?? ""}” (contents moved up)` };
    }

    case "create_event": {
      const { event } = calendar.createEvent({
        title: action.title,
        date: action.date,
        time: action.time ?? null,
        endTime: action.endTime ?? null,
        location: action.location,
        notes: action.notes,
        reminders: action.reminders,
        source: "agent",
      });
      return { data: load(), note: `Added “${event.title}” to the calendar`, calendarChanged: true };
    }

    case "update_event": {
      const before = calendar.getEvents().find((e) => e.id === action.eventId);
      if (!before) return { data: load(), note: "That event no longer exists" };
      calendar.updateEvent(action.eventId, {
        title: action.title,
        date: action.date,
        time: action.time,
        location: action.location,
        notes: action.notes,
        reminders: action.reminders,
      });
      return { data: load(), note: `Updated “${before.title}”`, calendarChanged: true };
    }

    case "delete_event": {
      const before = calendar.getEvents().find((e) => e.id === action.eventId);
      calendar.deleteEvent(action.eventId);
      return {
        data: load(),
        note: `Removed “${before?.title ?? "event"}” from the calendar`,
        calendarChanged: true,
      };
    }

    case "add_person": {
      const roles = ["self", "partner", "child", "relative", "friend", "other"] as const;
      const role = (roles as readonly string[]).includes(action.role)
        ? (action.role as (typeof roles)[number])
        : "other";
      createPerson({ name: action.name, role });
      return {
        data: load(),
        // Said plainly, because a person with no reference faces cannot be
        // recognised yet and silently doing nothing would look like a bug.
        note: `Added ${action.name} — add a few reference photos so I can recognise them`,
        photosChanged: true,
      };
    }

    default:
      return { data: load(), note: "Unknown action" };
  }
}
