// ---------------------------------------------------------------------------
// Recall — local-first data access.
// Backed by localStorage today; the async-friendly, folder+item shape maps
// cleanly onto a Supabase (+ pgvector) backend later without touching the UI.
// All mutators return the fresh RecallData so the component can setData(result).
// ---------------------------------------------------------------------------

import { nowIso, uid } from "../utils";
import { buildSeed } from "./seed";
import type { AgentAction, Folder, Item, RecallData } from "./types";

const KEY = "recall:v1";

// ----- persistence ---------------------------------------------------------

function load(): RecallData {
  if (typeof window === "undefined") return { folders: [], items: [] };
  try {
    const raw = window.localStorage.getItem(KEY);
    if (!raw) {
      const seeded = buildSeed();
      save(seeded);
      return seeded;
    }
    const data = JSON.parse(raw) as RecallData;
    return {
      folders: Array.isArray(data.folders) ? data.folders : [],
      items: Array.isArray(data.items) ? data.items : [],
    };
  } catch {
    return buildSeed();
  }
}

function save(data: RecallData): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(KEY, JSON.stringify(data));
}

export function getData(): RecallData {
  return load();
}

/** v1 is always local; the badge flips when a cloud backend is wired in. */
export function isLocal(): boolean {
  return true;
}

// ----- helpers -------------------------------------------------------------

export function folderPathString(folders: Folder[], folderId: string | null): string {
  if (!folderId) return "Inbox";
  const byId = new Map(folders.map((f) => [f.id, f]));
  const parts: string[] = [];
  let cur = byId.get(folderId);
  const guard = new Set<string>();
  while (cur && !guard.has(cur.id)) {
    guard.add(cur.id);
    parts.unshift(cur.name);
    cur = cur.parentId ? byId.get(cur.parentId) : undefined;
  }
  return parts.join(" › ") || "Inbox";
}

export function allTags(data: RecallData): string[] {
  const set = new Set<string>();
  for (const item of data.items) for (const t of item.tags) set.add(t);
  return [...set].sort((a, b) => a.localeCompare(b));
}

export function childFolders(folders: Folder[], parentId: string | null): Folder[] {
  return folders
    .filter((f) => f.parentId === parentId)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Every folder id under (and including) a given folder. */
export function descendantFolderIds(folders: Folder[], rootId: string): Set<string> {
  const out = new Set<string>([rootId]);
  let added = true;
  while (added) {
    added = false;
    for (const f of folders) {
      if (f.parentId && out.has(f.parentId) && !out.has(f.id)) {
        out.add(f.id);
        added = true;
      }
    }
  }
  return out;
}

/** Create the folders along a path (reusing matches case-insensitively). */
function ensurePath(data: RecallData, path: string[], auto: boolean): string | null {
  let parentId: string | null = null;
  for (const rawName of path) {
    const name = rawName.trim();
    if (!name) continue;
    const existing = data.folders.find(
      (f) => f.parentId === parentId && f.name.trim().toLowerCase() === name.toLowerCase(),
    );
    if (existing) {
      parentId = existing.id;
    } else {
      const created: Folder = {
        id: uid("fld"),
        name,
        parentId,
        autoGenerated: auto,
        createdAt: nowIso(),
      };
      data.folders.push(created);
      parentId = created.id;
    }
  }
  return parentId;
}

export function ensureFolderPath(path: string[], auto = true): { data: RecallData; folderId: string | null } {
  const data = load();
  const folderId = ensurePath(data, path, auto);
  save(data);
  return { data, folderId };
}

// ----- folder mutations ----------------------------------------------------

export function createFolder(name: string, parentId: string | null): { data: RecallData; folder: Folder } {
  const data = load();
  const folder: Folder = {
    id: uid("fld"),
    name: name.trim() || "Untitled",
    parentId,
    autoGenerated: false,
    createdAt: nowIso(),
  };
  data.folders.push(folder);
  save(data);
  return { data, folder };
}

export function renameFolder(id: string, name: string): RecallData {
  const data = load();
  const f = data.folders.find((x) => x.id === id);
  if (f) f.name = name.trim() || f.name;
  save(data);
  return data;
}

/** Delete a folder; its child folders and items lift up to its parent. */
export function deleteFolder(id: string): RecallData {
  const data = load();
  const target = data.folders.find((f) => f.id === id);
  if (!target) return data;
  const parentId = target.parentId;
  for (const f of data.folders) if (f.parentId === id) f.parentId = parentId;
  for (const it of data.items) if (it.folderId === id) it.folderId = parentId;
  data.folders = data.folders.filter((f) => f.id !== id);
  save(data);
  return data;
}

// ----- item mutations ------------------------------------------------------

export interface NewItemInput {
  title: string;
  body: string;
  summary: string;
  kind: Item["kind"];
  source: Item["source"];
  folderId: string | null;
  tags: string[];
  url?: string | null;
  attachment?: Item["attachment"];
  driveId?: string | null;
}

export function createItem(input: NewItemInput): { data: RecallData; item: Item } {
  const data = load();
  const ts = nowIso();
  const item: Item = {
    id: uid("itm"),
    title: input.title.trim() || "Untitled",
    body: input.body,
    summary: input.summary,
    kind: input.kind,
    source: input.source,
    folderId: input.folderId,
    tags: dedupeTags(input.tags),
    url: input.url ?? null,
    attachment: input.attachment ?? null,
    driveId: input.driveId ?? null,
    createdAt: ts,
    updatedAt: ts,
  };
  data.items.push(item);
  save(data);
  return { data, item };
}

export function updateItem(id: string, patch: Partial<Omit<Item, "id" | "createdAt">>): RecallData {
  const data = load();
  const it = data.items.find((x) => x.id === id);
  if (it) {
    Object.assign(it, patch);
    if (patch.tags) it.tags = dedupeTags(patch.tags);
    it.updatedAt = nowIso();
  }
  save(data);
  return data;
}

export function deleteItem(id: string): RecallData {
  const data = load();
  data.items = data.items.filter((x) => x.id !== id);
  save(data);
  return data;
}

export function moveItem(itemId: string, folderId: string | null): RecallData {
  return updateItem(itemId, { folderId });
}

export function setItemTags(itemId: string, tags: string[]): RecallData {
  return updateItem(itemId, { tags: dedupeTags(tags) });
}

function dedupeTags(tags: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of tags) {
    const t = raw.toLowerCase().trim().replace(/\s+/g, "-");
    if (t && !seen.has(t)) {
      seen.add(t);
      out.push(t);
    }
  }
  return out.slice(0, 12);
}

// ----- agent action execution ---------------------------------------------

/** Apply an agent-proposed action locally. Returns fresh data + a human note. */
export function executeAction(action: AgentAction): { data: RecallData; note: string } {
  switch (action.type) {
    case "create_folder": {
      const { data } = ensureFolderPath(action.path, false);
      return { data, note: `Created folder ${action.path.join(" › ")}` };
    }
    case "move_item": {
      const { folderId } = ensureFolderPath(action.path, true);
      const data = moveItem(action.itemId, folderId);
      const it = data.items.find((x) => x.id === action.itemId);
      return { data, note: `Moved “${it?.title ?? "item"}” to ${action.path.join(" › ")}` };
    }
    case "add_tags": {
      const data = load();
      const it = data.items.find((x) => x.id === action.itemId);
      if (it) {
        const next = setItemTags(action.itemId, [...it.tags, ...action.tags]);
        return { data: next, note: `Tagged “${it.title}” with ${action.tags.join(", ")}` };
      }
      return { data, note: "Item not found" };
    }
    case "remove_tags": {
      const data = load();
      const it = data.items.find((x) => x.id === action.itemId);
      if (it) {
        const next = setItemTags(
          action.itemId,
          it.tags.filter((t) => !action.tags.map((x) => x.toLowerCase()).includes(t.toLowerCase())),
        );
        return { data: next, note: `Removed ${action.tags.join(", ")} from “${it.title}”` };
      }
      return { data, note: "Item not found" };
    }
    case "create_note": {
      const { folderId } = ensureFolderPath(action.path, true);
      const { data, item } = createItem({
        title: action.title,
        body: action.body,
        summary: action.body.slice(0, 160),
        kind: "note",
        source: "manual",
        folderId,
        tags: action.tags,
      });
      return { data, note: `Created note “${item.title}”` };
    }
    default:
      return { data: load(), note: "Unknown action" };
  }
}
