// ---------------------------------------------------------------------------
// Recall — domain types.
// A personal RAG "second brain": capture anything, it auto-files + tags itself,
// then you find it by searching or by asking the agent (which can also act).
// Local-first (localStorage) now, structured so a Supabase + pgvector backend
// and a multi-user flip are a later switch, not a rewrite.
// ---------------------------------------------------------------------------

export type ItemKind = "note" | "link" | "image" | "file" | "drive";
export type ItemSource = "manual" | "drive" | "web";

export interface Attachment {
  name: string;
  /** MIME type or a friendly category. */
  type: string;
  size: number;
  /** Data URL (local mode) or storage path (cloud). Images inline here. */
  url?: string;
}

export interface Item {
  id: string;
  title: string;
  /** The full captured text / notes (markdown or plain). */
  body: string;
  /** One-line AI/heuristic summary shown on cards. */
  summary: string;
  kind: ItemKind;
  source: ItemSource;
  /** For links + Drive files: the canonical URL. */
  url?: string | null;
  /** Owning folder, or null for the loose Inbox. */
  folderId: string | null;
  tags: string[];
  attachment?: Attachment | null;
  /** Drive file id (dedupe) when source === "drive". */
  driveId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Folder {
  id: string;
  name: string;
  parentId: string | null;
  description?: string;
  /** True when created by the classifier rather than by hand. */
  autoGenerated: boolean;
  createdAt: string;
}

export interface RecallData {
  folders: Folder[];
  items: Item[];
}

/** What the classifier proposes for a freshly captured item. */
export interface Classification {
  title: string;
  summary: string;
  /** Folder path from root, e.g. ["Game Dev", "Engines"]. Created if missing. */
  folderPath: string[];
  tags: string[];
  engine: "ai" | "heuristic";
}

export interface ScoredItem {
  item: Item;
  score: number;
}

export interface SearchResult {
  items: ScoredItem[];
  folders: Folder[];
  tags: string[];
}

// ----- Agent -------------------------------------------------------------

/** A mutating action the agent proposes; executed client-side after confirm. */
export type AgentAction =
  | { type: "create_folder"; path: string[] }
  | { type: "move_item"; itemId: string; path: string[] }
  | { type: "add_tags"; itemId: string; tags: string[] }
  | { type: "remove_tags"; itemId: string; tags: string[] }
  | { type: "create_note"; title: string; body: string; path: string[]; tags: string[] };

export interface AgentReply {
  answer: string;
  /** Item ids the answer draws from — rendered as source chips. */
  citations: string[];
  actions: AgentAction[];
  engine: "ai" | "heuristic";
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  citations?: string[];
  actions?: AgentAction[];
  /** Marks actions the user already confirmed/dismissed so chips settle. */
  actionState?: "pending" | "applied" | "dismissed";
  engine?: "ai" | "heuristic";
}
