// ---------------------------------------------------------------------------
// Recall — domain types.
// A personal RAG "second brain": capture anything, it auto-files + tags itself,
// then you find it by searching or by asking the agent (which can also act).
// Local-first (localStorage) now, structured so a Supabase + pgvector backend
// and a multi-user flip are a later switch, not a rewrite.
//
// A folder is a WORKSPACE, not just a filter: it holds typed sections
// (sub-folders, notes, to-dos, links, logins, servers & sites) that stay
// collapsed to one quiet line each until you put something in them.
// ---------------------------------------------------------------------------

export type ItemKind =
  | "note"
  | "link"
  | "image"
  | "file"
  | "drive"
  | "todo"
  | "credential"
  | "website";

export type ItemSource = "manual" | "drive" | "web";

/** Which section of a folder workspace an item belongs to. */
export type SectionId = "subfolders" | "notes" | "todos" | "links" | "logins" | "websites";

/**
 * Kind → section. Files (images, video, PDFs, docs) live in Links & Resources
 * alongside URLs, because "a thing I saved to refer back to" is one idea.
 */
export const SECTION_OF: Record<ItemKind, Exclude<SectionId, "subfolders">> = {
  note: "notes",
  todo: "todos",
  link: "links",
  image: "links",
  file: "links",
  drive: "links",
  credential: "logins",
  website: "websites",
};

export interface Attachment {
  name: string;
  /** MIME type or a friendly category. */
  type: string;
  size: number;
  /**
   * Small inline preview only (image thumbnail data URL). The full file lives
   * in IndexedDB under `fileId` — localStorage would blow its ~5MB quota on the
   * first PDF, let alone a video.
   */
  url?: string;
  /** IndexedDB key for the full blob. */
  fileId?: string;
  /** "image" | "video" | "pdf" | "doc" | "file" — drives the icon and whether we read it. */
  category?: string;
}

/**
 * AES-GCM ciphertext, both halves base64.
 * LEGACY: passwords used to be sealed under a master password. Nothing writes
 * this any more -- existing ones are imported into `password` from Settings.
 */
export interface Cipher {
  iv: string;
  ct: string;
}

export interface Item {
  id: string;
  title: string;
  /** The full captured text / notes (markdown or plain). */
  body: string;
  /** One-line AI/heuristic summary shown on cards. */
  summary: string;
  kind: ItemKind;
  source: ItemSource;
  /** For links + Drive files: the canonical URL. */
  url?: string | null;
  /** Owning folder, or null for the loose Inbox. */
  folderId: string | null;
  tags: string[];
  attachment?: Attachment | null;
  /** Drive file id (dedupe) when source === "drive". */
  driveId?: string | null;
  /** To-do completion. */
  done?: boolean;
  /**
   * Structured, searchable, PLAINTEXT fields — server host/ssh/provider,
   * site registrar/renewal, credential username/url. Never a password.
   */
  fields?: Record<string, string>;
  /**
   * The saved password on a credential, in the clear.
   * Deliberately readable: the whole point is that you can recover it later,
   * from the card or from Settings, without a second password to remember.
   * Never indexed by search (see `search.ts`) and never sent anywhere.
   */
  password?: string | null;
  /** LEGACY ciphertext, kept only so it can be imported into `password`. */
  secret?: Cipher | null;
  /**
   * Text read out of the thing itself — a PDF's contents, a .docx, a page's
   * readable body, a described image. This is what makes the RAG work: the
   * agent and the search index read this, not just the title you typed.
   * Video is stored but never extracted (see `extractStatus`).
   */
  extract?: string;
  /** "ok" | "pending" | "unsupported" | "failed" — surfaced on the row. */
  extractStatus?: "ok" | "pending" | "unsupported" | "failed";
  /** Person ids the vision pass recognised in a photo. */
  people?: string[];
  /** The photo category rule that filed it, when one did. */
  photoCategoryId?: string | null;
  /** Look-alike fingerprint of an image item; syncs, so duplicates are caught on every device. */
  fingerprint?: string;
  /** Set once this photo has been copied to the Google Drive backup. */
  driveBackupId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Folder {
  id: string;
  name: string;
  parentId: string | null;
  description?: string;
  /** True when created by the classifier rather than by hand. */
  autoGenerated: boolean;
  /** Optional accent for the folder tile, e.g. "brand" | "core" | "support". */
  accent?: string;
  /** Icon key from the folder icon set — chosen when the folder is created. */
  icon?: string;
  /**
   * Marks a folder the app itself manages. "photos" is the camera-roll root:
   * it keeps its own warm palette everywhere it appears and opens the Photos
   * surface instead of the ordinary workspace, so renaming it does not quietly
   * turn it back into a normal folder.
   */
  role?: "photos";
  /**
   * Which sections this folder shows. Undefined on older folders, which is why
   * `visibleSections` also forces on any section that actually holds something —
   * turning a section off must never hide data.
   */
  sections?: SectionId[];
  createdAt: string;
}

/** Canonical order for the section stack and the add-section menu. */
export const SECTION_ORDER: SectionId[] = ["subfolders", "notes", "todos", "links", "logins", "websites"];

export interface RecallData {
  folders: Folder[];
  items: Item[];
}

/** What the classifier proposes for a freshly captured item. */
export interface Classification {
  title: string;
  summary: string;
  /** Folder path from root, e.g. ["Game Dev", "Engines"]. Created if missing. */
  folderPath: string[];
  tags: string[];
  engine: "ai" | "heuristic";
}

export interface ScoredItem {
  item: Item;
  score: number;
}

export interface SearchResult {
  items: ScoredItem[];
  folders: Folder[];
  tags: string[];
}

// ----- Agent -------------------------------------------------------------

/** A mutating action the agent proposes; executed client-side after confirm. */
export type AgentAction =
  | { type: "create_folder"; path: string[] }
  | { type: "move_item"; itemId: string; path: string[] }
  /** Bulk move — "put these five bots in FX Bots" is one action, one confirm. */
  | { type: "move_items"; itemIds: string[]; path: string[] }
  | { type: "add_tags"; itemId: string; tags: string[] }
  | { type: "remove_tags"; itemId: string; tags: string[] }
  | { type: "create_note"; title: string; body: string; path: string[]; tags: string[] }
  | { type: "rename_item"; itemId: string; title: string }
  | { type: "edit_note"; itemId: string; body: string }
  | { type: "rename_folder"; folderId: string; name: string }
  /** Move a whole folder (and everything under it) under another path. */
  | { type: "move_folder"; folderId: string; path: string[] }
  /** Fold one folder's contents into another, then remove the empty source. */
  | { type: "merge_folders"; sourceId: string; targetPath: string[] }
  | { type: "delete_item"; itemId: string }
  /** Folder delete lifts children to the parent — nothing is destroyed. */
  | { type: "delete_folder"; folderId: string }
  // ----- calendar ---------------------------------------------------------
  // The assistant reads the calendar as context and writes to it the same way
  // it writes to the knowledge base: as a proposal the user confirms.
  | {
      type: "create_event";
      title: string;
      /** Local day, "YYYY-MM-DD". */
      date: string;
      /** Local "HH:MM", or null for all-day. */
      time?: string | null;
      endTime?: string | null;
      location?: string;
      notes?: string;
      /** Minutes before the start. */
      reminders?: number[];
    }
  | {
      type: "update_event";
      eventId: string;
      title?: string;
      date?: string;
      time?: string | null;
      location?: string;
      notes?: string;
      reminders?: number[];
    }
  | { type: "delete_event"; eventId: string }
  // ----- photos -----------------------------------------------------------
  /** Register someone so their photos can be recognised and filed. */
  | { type: "add_person"; name: string; role: string };

/** Actions that remove or overwrite something get a louder confirmation. */
export const DESTRUCTIVE_ACTIONS: ReadonlySet<AgentAction["type"]> = new Set([
  "delete_item",
  "delete_folder",
  "merge_folders",
  "edit_note",
  "delete_event",
]);

export interface AgentReply {
  answer: string;
  /** Item ids the answer draws from — rendered as source chips. */
  citations: string[];
  actions: AgentAction[];
  engine: "ai" | "heuristic";
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  citations?: string[];
  actions?: AgentAction[];
  /** Marks actions the user already confirmed/dismissed so chips settle. */
  actionState?: "pending" | "applied" | "dismissed";
  engine?: "ai" | "heuristic";
}
