"use client";

// ---------------------------------------------------------------------------
// Artist Voice Studio — find a voice, keep it, perform with it.
//
// The pipeline is real end to end, and one part of it is narrower than people
// expect, so the screen says so where the decision is made rather than in a
// footnote: AuK is a SPEECH model. It clones a voice and performs written words
// in it. It does not sing, and no amount of prompting makes it sing. What this
// tool therefore produces is a spoken or rapped vocal over music generated by
// YuE2 — which is a real record for some genres and honestly the wrong tool for
// others.
//
// The voice layer is one module behind `speak()` in the studio context, so a
// singing-voice model can be added later as a second engine without any of this
// screen changing shape.
// ---------------------------------------------------------------------------

import { useState } from "react";
import { Icon } from "../../icons";
import { type Clip, fileToClip } from "@/lib/music-creator/audio";
import { mix, registerVoice, searchArtist } from "@/lib/music-creator/client";
import { toolById } from "@/lib/music-creator/tools";
import type { ToolProps } from "@/lib/music-creator/tools";
import type { ArtistTrack, Render, VoiceProfile } from "@/lib/music-creator/types";
import { ClipPicker } from "../ClipPicker";
import { Field, ServerNotice, Takes, Text, WriterNote, useWriter } from "../parts";
import { useStudio } from "../studio";

export function ArtistVoice({ project, update, setData }: ToolProps) {
  const { voices, speak, render, running, fileUrl } = useStudio();
  const tool = toolById("artist-voice");
  const writer = useWriter();

  const voice = voices.find((v) => v.id === project.voiceId) ?? null;
  const data = (project.data ?? {}) as {
    text?: string;
    instruction?: string;
    seconds?: number;
    description?: string;
  };

  return (
    <div>
      {tool && <ServerNotice tool={tool} />}

      <div className="mc-steps">
        <Step n={1} title="The voice" state={voice ? "done" : "on"}>
          {voice ? <ChosenVoice voice={voice} onChange={() => update({ voiceId: undefined })} /> : <FindVoice onSaved={(v) => update({ voiceId: v.id })} project={project} />}
        </Step>

        <Step n={2} title="The words" state={!voice ? "off" : data.text ? "done" : "on"}>
          <Words
            voice={voice}
            text={data.text ?? ""}
            instruction={data.instruction ?? ""}
            description={data.description ?? ""}
            writer={writer}
            onChange={(patch) => setData(patch)}
          />
        </Step>

        <Step n={3} title="The music" state={project.request.style ? "done" : voice ? "on" : "off"}>
          <Music
            style={project.request.style}
            lyrics={project.request.lyrics}
            description={data.description ?? ""}
            writer={writer}
            onDescription={(description) => setData({ description })}
            onStyle={(style) => update({ request: { ...project.request, style } })}
            onLyrics={(lyrics) => update({ request: { ...project.request, lyrics } })}
          />
        </Step>

        <Step n={4} title="Perform and combine" state={project.renders.length ? "done" : "on"}>
          <Perform
            project={project}
            voice={voice}
            text={data.text ?? ""}
            instruction={data.instruction ?? ""}
            seconds={data.seconds}
            onSeconds={(seconds) => setData({ seconds })}
            speak={speak}
            render={render}
            busy={!!running}
          />
        </Step>
      </div>

      <section className="mc-panel">
        <div className="mc-panel-h">
          <h3>Takes</h3>
          <span className="mc-tag2">vocal · music · combined</span>
        </div>
        <Takes renders={project.renders} empty="Nothing performed yet." />
        <Combine project={project} busy={!!running} fileUrl={fileUrl} />
      </section>

      <p className="mc-note">
        A cloned voice of a real person is theirs, not yours. This is a private studio tool: keep what you make here to
        yourself rather than publishing or selling it as that artist, and do not pass it off as a real recording.
      </p>
    </div>
  );
}

// ----- step chrome ---------------------------------------------------------

function Step({ n, title, state, children }: { n: number; title: string; state: "on" | "off" | "done"; children: React.ReactNode }) {
  return (
    <div className={`mc-step ${state === "done" ? "is-done" : state === "on" ? "is-on" : ""}`}>
      <div className="mc-step-n">{state === "done" ? <Icon.Check width={12} height={12} /> : n}</div>
      <div className="mc-step-b">
        <div className="mc-step-t">{title}</div>
        {children}
      </div>
    </div>
  );
}

// ----- step 1: the voice ---------------------------------------------------

function ChosenVoice({ voice, onChange }: { voice: VoiceProfile; onChange: () => void }) {
  return (
    <div className="mc-row">
      <div className="mc-item-m">
        <strong>{voice.name}</strong>
        <span>
          {voice.artist ? `${voice.artist} · ` : ""}
          {voice.durationS ? `${voice.durationS.toFixed(1)}s reference · ` : ""}
          saved {new Date(voice.created).toLocaleDateString()}
        </span>
      </div>
      {voice.clipDataUrl && <audio controls preload="none" src={voice.clipDataUrl} style={{ height: 32 }} />}
      <button type="button" className="mc-btn mc-btn-s" onClick={onChange}>
        Use a different voice
      </button>
    </div>
  );
}

function FindVoice({ onSaved, project }: { onSaved: (voice: VoiceProfile) => void; project: ToolProps["project"] }) {
  const { voices, saveVoice, server, runAndFile, fileUrl } = useStudio();
  const [query, setQuery] = useState("");
  const [tracks, setTracks] = useState<ArtistTrack[]>([]);
  const [searching, setSearching] = useState(false);
  const [clip, setClip] = useState<Clip | null>(null);
  const [clipNote, setClipNote] = useState("");
  const [name, setName] = useState("");
  const [artist, setArtist] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // The term is passed in from the keydown handler rather than read from state:
  // a fast typist can hit Enter in the same tick as the last keystroke, and the
  // handler's closure would then still hold the previous value.
  async function doSearch(term = query) {
    if (!term.trim()) return;
    setSearching(true);
    setError(null);
    try {
      const { tracks } = await searchArtist(term.trim());
      setTracks(tracks);
      if (!tracks.length) setError("Nothing came back for that. Try the artist's name plus a song title.");
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSearching(false);
    }
  }

  async function takeTrack(track: ArtistTrack) {
    if (!track.previewUrl) return;
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/music-creator/artist?preview=${encodeURIComponent(track.previewUrl)}`);
      if (!res.ok) throw new Error(`The preview could not be fetched (${res.status}).`);
      setClip(await fileToClip(await res.blob()));
      setClipNote(`30s preview of "${track.title}"`);
      setArtist(track.artist);
      if (!name) setName(track.artist);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function takeFile(file: File) {
    setBusy(true);
    setError(null);
    try {
      setClip(await fileToClip(file));
      setClipNote(file.name);
      if (!name) setName(file.name.replace(/\.[^.]+$/, ""));
    } catch {
      setError("That file could not be decoded as audio.");
    } finally {
      setBusy(false);
    }
  }

  /**
   * Pull the voice out of a clip that has music under it.
   *
   * A catalogue preview is a finished record, and cloning from a mixed record
   * clones the mix. AuK's own separation is the fix, which is why this is one
   * button rather than advice.
   */
  async function isolate() {
    if (!clip) return;
    setBusy(true);
    setError(null);
    try {
      const dataUrl = await blobOfClip(clip);
      const record = await runAndFile(project.id, "stem", "jobs/separate", { audio_b64: dataUrl, mode: "vocals" }, "Isolated vocal");
      if (!record) return;
      if (record.error) throw new Error(record.error);
      if (!record.fileId) throw new Error("Separation finished without returning audio.");
      const res = await fetch(fileUrl(record.fileId));
      setClip(await fileToClip(await res.blob()));
      setClipNote(`${clipNote} · vocals isolated`);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  async function cloneIt(dataUrl: string, seconds: number) {
    if (!name.trim()) {
      setError("Give the voice a name first.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const { voiceRefId } = await registerVoice({ name: name.trim(), audioDataUrl: dataUrl });
      const saved: VoiceProfile = {
        id: `v_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`,
        name: name.trim(),
        artist: artist || undefined,
        source: clipNote.includes("preview") ? "preview" : "upload",
        sourceNote: clipNote,
        created: Date.now(),
        durationS: seconds,
        clipDataUrl: dataUrl,
        serverRefId: voiceRefId,
      };
      saveVoice(saved);
      onSaved(saved);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div>
      {voices.length > 0 && (
        <div className="mc-panel" style={{ marginBottom: 12 }}>
          <div className="mc-panel-h">
            <h3>From the library</h3>
            <span className="mc-tag2">already cloned — nothing to process</span>
          </div>
          <div className="mc-row">
            {voices.map((v) => (
              <button key={v.id} type="button" className="mc-btn mc-btn-s" onClick={() => onSaved(v)}>
                <Icon.Mic width={12} height={12} /> {v.name}
              </button>
            ))}
          </div>
        </div>
      )}

      <div className="mc-panel">
        <div className="mc-panel-h">
          <h3>Find a new voice</h3>
        </div>

        <div className="mc-row">
          <input
            className="mc-input"
            style={{ flex: 1, minWidth: 200 }}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") void doSearch(e.currentTarget.value);
            }}
            placeholder="Artist name, or artist and song"
          />
          <button type="button" className="mc-btn" onClick={() => void doSearch()} disabled={searching}>
            <Icon.Search width={13} height={13} /> {searching ? "Searching…" : "Search"}
          </button>
          <label className="mc-btn">
            <Icon.Upload width={13} height={13} /> Upload audio
            <input
              type="file"
              accept="audio/*"
              hidden
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) void takeFile(file);
              }}
            />
          </label>
        </div>

        {tracks.length > 0 && (
          <div className="mc-tracks" style={{ marginTop: 12 }}>
            {tracks.map((t) => (
              <button key={t.id} type="button" className="mc-track" onClick={() => takeTrack(t)} disabled={!t.previewUrl || busy}>
                {t.artwork ? <img src={t.artwork} alt="" /> : <span className="mc-track-art" />}
                <span className="mc-track-m">
                  <strong>{t.title}</strong>
                  <span>
                    {t.artist}
                    {t.previewUrl ? "" : " · no preview"}
                  </span>
                </span>
              </button>
            ))}
          </div>
        )}

        <p className="mc-note">
          A catalogue preview is a finished record, so the cleanest reference is an interview or a spoken clip you
          upload. If all you have is the record, isolate the vocal below first.
        </p>

        {clip && (
          <div style={{ marginTop: 14 }}>
            <Field label="Reference clip" hint={clipNote}>
              <div />
            </Field>
            <ClipPicker clip={clip} onUse={cloneIt} busy={busy} useLabel="Clone and save to the library" />
            <div className="mc-row" style={{ marginTop: 10 }}>
              <input
                className="mc-input"
                style={{ flex: 1, minWidth: 180 }}
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Name this voice"
              />
              <button
                type="button"
                className="mc-btn mc-btn-s"
                onClick={isolate}
                disabled={busy || !server?.reachable}
                title="Run AuK's separation over the clip and keep only the voice"
              >
                <Icon.Layers width={12} height={12} /> Isolate the vocal
              </button>
            </div>
          </div>
        )}

        {error && <p className="mc-note is-bad">{error}</p>}
      </div>
    </div>
  );
}

/** Re-encode a decoded clip whole, for a round trip through the server. */
async function blobOfClip(clip: Clip): Promise<string> {
  const { cutToWavDataUrl } = await import("@/lib/music-creator/audio");
  return cutToWavDataUrl(clip.buffer, 0, clip.durationS);
}

// ----- step 2: the words ---------------------------------------------------

function Words({
  voice,
  text,
  instruction,
  description,
  writer,
  onChange,
}: {
  voice: VoiceProfile | null;
  text: string;
  instruction: string;
  description: string;
  writer: ReturnType<typeof useWriter>;
  onChange: (patch: Record<string, unknown>) => void;
}) {
  return (
    <div className="mc-panel">
      <p className="mc-note is-warn" style={{ marginTop: 0 }}>
        AuK performs written words in a cloned voice by speaking them. It cannot sing — so this vocal will be spoken or
        rapped over the music, not sung.
      </p>
      <Field label="What the voice performs" hint="the words only — no stage directions">
        <Text rows={8} value={text} onChange={(v) => onChange({ text: v })} placeholder="The lines this voice delivers." />
      </Field>
      <Field label="Delivery" hint="pace, energy, emotion, spacing">
        <Text value={instruction} onChange={(v) => onChange({ instruction: v })} placeholder="Low and unhurried, leaving space between lines." />
      </Field>
      <div className="mc-row">
        <button
          type="button"
          className="mc-btn"
          disabled={writer.busy || !voice}
          onClick={async () => {
            const result = await writer.run("vocal-direction", { lyrics: text, brief: description, vocal: instruction });
            if (!result) return;
            onChange({
              text: typeof result.text === "string" ? result.text : text,
              instruction: typeof result.instruction === "string" ? result.instruction : instruction,
            });
          }}
        >
          <Icon.Sparkles width={13} height={13} /> Direct the performance
        </button>
      </div>
      <WriterNote engine={writer.engine} warning={writer.warning} error={writer.error} />
    </div>
  );
}

// ----- step 3: the music ---------------------------------------------------

function Music({
  style,
  lyrics,
  description,
  writer,
  onDescription,
  onStyle,
  onLyrics,
}: {
  style: string;
  lyrics: string;
  description: string;
  writer: ReturnType<typeof useWriter>;
  onDescription: (v: string) => void;
  onStyle: (v: string) => void;
  onLyrics: (v: string) => void;
}) {
  return (
    <div className="mc-panel">
      <Field label="Describe the song" hint="genre, mood, tempo, energy, instruments">
        <Text
          rows={2}
          value={description}
          onChange={onDescription}
          placeholder="Moody trap soul, 72 BPM, sparse piano, heavy 808s — a bed for a spoken vocal."
        />
      </Field>
      <Field label="Style line" hint="what YuE2 plays under the vocal">
        <Text rows={3} value={style} onChange={onStyle} placeholder="English, moody trap soul, 72 BPM, sparse piano, heavy 808s, no lead vocal" />
      </Field>
      <Field label="Sung lyrics" hint="optional — leave empty for an instrumental bed">
        <Text rows={6} value={lyrics} onChange={onLyrics} placeholder={"[Chorus]\nhook sung by the model, under the cloned voice"} />
      </Field>
      <p className="mc-note">
        For a bed under a spoken vocal, say so in the style line — an instrumental leaves room for the cloned voice
        instead of competing with a sung lead.
      </p>
      <WriterNote engine={writer.engine} warning={null} error={null} />
    </div>
  );
}

// ----- step 4: perform -----------------------------------------------------

function Perform({
  project,
  voice,
  text,
  instruction,
  seconds,
  onSeconds,
  speak,
  render,
  busy,
}: {
  project: ToolProps["project"];
  voice: VoiceProfile | null;
  text: string;
  instruction: string;
  seconds?: number;
  onSeconds: (v: number) => void;
  speak: ReturnType<typeof useStudio>["speak"];
  render: ReturnType<typeof useStudio>["render"];
  busy: boolean;
}) {
  return (
    <div className="mc-panel">
      <Field label="Vocal length" hint="seconds AuK should generate">
        <input
          className="mc-input"
          type="number"
          min={1}
          max={60}
          value={seconds ?? 12}
          onChange={(e) => onSeconds(Number(e.target.value) || 12)}
          style={{ maxWidth: 140 }}
        />
      </Field>
      <div className="mc-row">
        <button
          type="button"
          className="mc-btn"
          disabled={busy || !voice || !text.trim()}
          onClick={() => voice && void speak(project.id, { voice, text, instruction, seconds: seconds ?? 12 }, `Vocal · ${voice.name}`)}
        >
          <Icon.Mic width={13} height={13} /> Perform the vocal
        </button>
        <button
          type="button"
          className="mc-btn"
          disabled={busy || !project.request.style.trim()}
          onClick={() => void render(project.id, project.request, "Music bed")}
        >
          <Icon.Note width={13} height={13} /> Render the music
        </button>
      </div>
      <p className="mc-note">
        One GPU, one job at a time: run them in whichever order you like, but they queue. Combine them below once both
        exist.
      </p>
    </div>
  );
}

// ----- combining -----------------------------------------------------------

function Combine({ project, busy, fileUrl }: { project: ToolProps["project"]; busy: boolean; fileUrl: (id: string) => string }) {
  const { patchProject } = useStudio();
  const [working, setWorking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [vocalGain, setVocalGain] = useState(0);
  const [musicGain, setMusicGain] = useState(-3);
  const [offset, setOffset] = useState(0);

  const vocals = project.renders.filter((r) => r.kind === "vocal" && r.fileId);
  const music = project.renders.filter((r) => r.kind === "song" && r.fileId);
  const [vocalId, setVocalId] = useState("");
  const [musicId, setMusicId] = useState("");

  if (!vocals.length || !music.length) return null;

  const vocal = vocalId || (vocals[0].fileId as string);
  const bed = musicId || (music[0].fileId as string);

  async function combine() {
    setWorking(true);
    setError(null);
    try {
      const fileId = await mix({ musicFileId: bed, vocalFileId: vocal, vocalGainDb: vocalGain, musicGainDb: musicGain, offsetS: offset });
      const record: Render = {
        id: `r_${Date.now().toString(36)}`,
        kind: "mix",
        label: "Vocal over music",
        fileId,
        jobId: null,
        created: Date.now(),
      };
      // Against the live project: a render that finished while the mix was
      // running is still in the list this adds to.
      patchProject(project.id, (p) => ({ renders: [record, ...p.renders] }));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setWorking(false);
    }
  }

  return (
    <div className="mc-panel" style={{ marginTop: 14 }}>
      <div className="mc-panel-h">
        <h3>Combine</h3>
        <span className="mc-tag2">vocal over the bed, mixed on the server</span>
      </div>
      <div className="mc-cols">
        <Field label="Vocal">
          <select className="mc-input" value={vocal} onChange={(e) => setVocalId(e.target.value)}>
            {vocals.map((r) => (
              <option key={r.id} value={r.fileId as string}>
                {r.label}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Music">
          <select className="mc-input" value={bed} onChange={(e) => setMusicId(e.target.value)}>
            {music.map((r) => (
              <option key={r.id} value={r.fileId as string}>
                {r.label}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Vocal gain" hint="dB">
          <input className="mc-input" type="number" value={vocalGain} onChange={(e) => setVocalGain(Number(e.target.value))} />
        </Field>
        <Field label="Music gain" hint="dB">
          <input className="mc-input" type="number" value={musicGain} onChange={(e) => setMusicGain(Number(e.target.value))} />
        </Field>
        <Field label="Vocal starts at" hint="seconds into the bed">
          <input className="mc-input" type="number" step="0.1" value={offset} onChange={(e) => setOffset(Number(e.target.value))} />
        </Field>
      </div>
      <div className="mc-row">
        <button type="button" className="mc-btn mc-btn-go" onClick={combine} disabled={working || busy}>
          {working ? "Mixing…" : "Combine into one track"}
        </button>
        <a className="mc-btn mc-btn-s" href={fileUrl(bed)} download>
          <Icon.Download width={12} height={12} /> The bed on its own
        </a>
      </div>
      {error && <p className="mc-note is-bad">{error}</p>}
    </div>
  );
}
